package com.yongjia.mybatis.dao;

import com.yongjia.mybatis.model.Saler;

public interface SalerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saler
     *
     * @mbggenerated Sun Jun 14 21:40:21 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saler
     *
     * @mbggenerated Sun Jun 14 21:40:21 CST 2015
     */
    int insert(Saler record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saler
     *
     * @mbggenerated Sun Jun 14 21:40:21 CST 2015
     */
    int insertSelective(Saler record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saler
     *
     * @mbggenerated Sun Jun 14 21:40:21 CST 2015
     */
    Saler selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saler
     *
     * @mbggenerated Sun Jun 14 21:40:21 CST 2015
     */
    int updateByPrimaryKeySelective(Saler record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saler
     *
     * @mbggenerated Sun Jun 14 21:40:21 CST 2015
     */
    int updateByPrimaryKey(Saler record);
}