package com.yongjia.mybatis.dao;

import com.yongjia.mybatis.model.WxMsgItem;

public interface WxMsgItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_msg_item
     *
     * @mbggenerated Sun Jun 14 21:40:21 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_msg_item
     *
     * @mbggenerated Sun Jun 14 21:40:21 CST 2015
     */
    int insert(WxMsgItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_msg_item
     *
     * @mbggenerated Sun Jun 14 21:40:21 CST 2015
     */
    int insertSelective(WxMsgItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_msg_item
     *
     * @mbggenerated Sun Jun 14 21:40:21 CST 2015
     */
    WxMsgItem selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_msg_item
     *
     * @mbggenerated Sun Jun 14 21:40:21 CST 2015
     */
    int updateByPrimaryKeySelective(WxMsgItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_msg_item
     *
     * @mbggenerated Sun Jun 14 21:40:21 CST 2015
     */
    int updateByPrimaryKeyWithBLOBs(WxMsgItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_msg_item
     *
     * @mbggenerated Sun Jun 14 21:40:21 CST 2015
     */
    int updateByPrimaryKey(WxMsgItem record);
}