package com.yongjia.dao;

import java.util.List;

import com.yongjia.model.AdminUser;

public interface AdminUserMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table admin_user
	 * @mbggenerated  Sun Jun 07 15:16:33 CST 2015
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table admin_user
	 * @mbggenerated  Sun Jun 07 15:16:33 CST 2015
	 */
	int insert(AdminUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table admin_user
	 * @mbggenerated  Sun Jun 07 15:16:33 CST 2015
	 */
	int insertSelective(AdminUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table admin_user
	 * @mbggenerated  Sun Jun 07 15:16:33 CST 2015
	 */
	List<AdminUser> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table admin_user
	 * @mbggenerated  Sun Jun 07 15:16:33 CST 2015
	 */
	AdminUser selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table admin_user
	 * @mbggenerated  Sun Jun 07 15:16:33 CST 2015
	 */
	int updateByPrimaryKeySelective(AdminUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table admin_user
	 * @mbggenerated  Sun Jun 07 15:16:33 CST 2015
	 */
	int updateByPrimaryKey(AdminUser record);
}