package com.yongjia.dao;

import java.util.List;

import com.yongjia.model.CarHallPic;

public interface CarHallPicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_hall_pic
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    Long deleteByPrimaryKey(Long id);
    
    Long deleteByCarHallId(Long carHallId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_hall_pic
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    Long insert(CarHallPic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_hall_pic
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    Long insertSelective(CarHallPic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_hall_pic
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    CarHallPic selectByPrimaryKey(Long id);
    
    List<CarHallPic> selectByHallId(Long hallId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_hall_pic
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    Long updateByPrimaryKeySelective(CarHallPic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_hall_pic
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    Long updateByPrimaryKey(CarHallPic record);
}