package com.yongjia.dao;

import com.yongjia.model.CarHallModel;

public interface CarHallModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_hall_model
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_hall_model
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    int insert(CarHallModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_hall_model
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    int insertSelective(CarHallModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_hall_model
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    CarHallModel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_hall_model
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    int updateByPrimaryKeySelective(CarHallModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_hall_model
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    int updateByPrimaryKey(CarHallModel record);
}