package com.yongjia.dao;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.yongjia.model.CarHall;

public interface CarHallMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table car_hall
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    Long deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table car_hall
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    Long insert(CarHall record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table car_hall
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    Long insertSelective(CarHall record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table car_hall
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    CarHall selectByPrimaryKey(Long id);

    List<CarHall> selectByCondition(@Param("typeName") String typeName, @Param("importFlag") Integer importFlag,
            @Param("page") Map page);

    Long countByCondition(@Param("typeName") String typeName, @Param("importFlag") Integer importFlag);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table car_hall
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    Long updateByPrimaryKeySelective(CarHall record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table car_hall
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    Long updateByPrimaryKey(CarHall record);
}