package com.yongjia.dao;

import com.yongjia.model.CarHall;

public interface CarHallMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_hall
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_hall
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    int insert(CarHall record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_hall
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    int insertSelective(CarHall record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_hall
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    CarHall selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_hall
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    int updateByPrimaryKeySelective(CarHall record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_hall
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    int updateByPrimaryKey(CarHall record);
}