package com.yongjia.dao;

import com.yongjia.model.CarHallPic;

public interface CarHallPicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_hall_pic
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_hall_pic
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    int insert(CarHallPic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_hall_pic
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    int insertSelective(CarHallPic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_hall_pic
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    CarHallPic selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_hall_pic
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    int updateByPrimaryKeySelective(CarHallPic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_hall_pic
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    int updateByPrimaryKey(CarHallPic record);
}