package com.yongjia.dao;

import com.yongjia.model.CarModel;

public interface CarModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_model
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_model
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    int insert(CarModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_model
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    int insertSelective(CarModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_model
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    CarModel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_model
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    int updateByPrimaryKeySelective(CarModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_model
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    int updateByPrimaryKey(CarModel record);
}