package com.yongjia.dao;

import java.util.List;

import com.yongjia.model.CarModelParam;

public interface CarModelParamMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_model_param
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    Long deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_model_param
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    Long insert(CarModelParam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_model_param
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    Long insertSelective(CarModelParam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_model_param
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    CarModelParam selectByPrimaryKey(Long id);
    
    List<CarModelParam> selectByModelId(Long modelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_model_param
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    Long updateByPrimaryKeySelective(CarModelParam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_model_param
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    Long updateByPrimaryKey(CarModelParam record);
}