package com.yongjia.dao;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.yongjia.model.CarType;

public interface CarTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_type
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    Long deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_type
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    Long insert(CarType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_type
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    Long insertSelective(CarType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_type
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    CarType selectByPrimaryKey(Long id);
    
    Long countByCondition(@Param("importFlag")Integer importFlag,@Param("canEditFlag")Integer canEditFlag);
    List<CarType> selectByCondition(@Param("importFlag")Integer importFlag,@Param("canEditFlag")Integer canEditFlag,@Param("page")Map page);
    
    List<CarType> selectByImportFlag(@Param("importFlag")Integer importFlag);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_type
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    Long updateByPrimaryKeySelective(CarType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_type
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    Long updateByPrimaryKey(CarType record);
}