package com.yongjia.dao;

import com.yongjia.model.CarType;

public interface CarTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_type
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_type
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    int insert(CarType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_type
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    int insertSelective(CarType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_type
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    CarType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_type
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    int updateByPrimaryKeySelective(CarType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_type
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    int updateByPrimaryKey(CarType record);
}