package com.yongjia.dao;

import com.yongjia.model.GiftPic;

public interface GiftPicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gift_pic
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gift_pic
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    int insert(GiftPic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gift_pic
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    int insertSelective(GiftPic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gift_pic
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    GiftPic selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gift_pic
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    int updateByPrimaryKeySelective(GiftPic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gift_pic
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    int updateByPrimaryKey(GiftPic record);
}