package com.yongjia.dao;

import com.yongjia.model.Gift;

public interface GiftMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gift
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gift
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    int insert(Gift record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gift
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    int insertSelective(Gift record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gift
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    Gift selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gift
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    int updateByPrimaryKeySelective(Gift record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gift
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    int updateByPrimaryKeyWithBLOBs(Gift record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gift
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    int updateByPrimaryKey(Gift record);
}