package com.yongjia.dao;

import java.util.List;

import com.yongjia.model.MemberCar;

public interface MemberCarMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_car
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    Long deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_car
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    Long insert(MemberCar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_car
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    Long insertSelective(MemberCar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_car
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    MemberCar selectByPrimaryKey(Long id);
    
    List<MemberCar> selectByMemberId(Long memberId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_car
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    Long updateByPrimaryKeySelective(MemberCar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_car
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    Long updateByPrimaryKey(MemberCar record);
}