package com.yongjia.dao;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.yongjia.model.MemberPointRecord;

public interface MemberPointRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_point_record
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    Long deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_point_record
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    Long insert(MemberPointRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_point_record
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    Long insertSelective(MemberPointRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_point_record
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    MemberPointRecord selectByPrimaryKey(Long id);
    
    List<MemberPointRecord> selectByPoolIdAndType(@Param("pointPoolId")Long pointPoolId, @Param("type")Integer type, @Param("page")Map page);
    Long countByPoolIdAndType(@Param("pointPoolId")Long pointPoolId, @Param("type")Integer type);

    List<MemberPointRecord> selectByPoolIdAndMemberId(@Param("pointPoolId")Long pointPoolId, @Param("memberId")Long memberId, @Param("page")Map page);
    Long countByPoolIdAndMemberId(@Param("pointPoolId")Long pointPoolId, @Param("memberId")Long memberId);
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_point_record
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    Long updateByPrimaryKeySelective(MemberPointRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_point_record
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    Long updateByPrimaryKeyWithBLOBs(MemberPointRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_point_record
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    Long updateByPrimaryKey(MemberPointRecord record);
}