package com.yongjia.dao;

import com.yongjia.model.MemberPointRecord;

public interface MemberPointRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_point_record
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_point_record
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    int insert(MemberPointRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_point_record
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    int insertSelective(MemberPointRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_point_record
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    MemberPointRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_point_record
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    int updateByPrimaryKeySelective(MemberPointRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_point_record
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    int updateByPrimaryKeyWithBLOBs(MemberPointRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_point_record
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    int updateByPrimaryKey(MemberPointRecord record);
}