package com.yongjia.dao;

import org.apache.ibatis.annotations.Param;

import com.yongjia.model.MemberPoint;

public interface MemberPointMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_point
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_point
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    int insert(MemberPoint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_point
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    int insertSelective(MemberPoint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_point
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    MemberPoint selectByPrimaryKey(Long id);
    
    MemberPoint selectByMemberIdAndPoolId(@Param("memberId")Long memberId, @Param("pointPoolId")Long pointPoolId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_point
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    int updateByPrimaryKeySelective(MemberPoint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_point
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    int updateByPrimaryKey(MemberPoint record);
}