package com.yongjia.dao;

import com.yongjia.model.MemberCar;

public interface MemberCarMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_car
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_car
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    int insert(MemberCar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_car
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    int insertSelective(MemberCar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_car
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    MemberCar selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_car
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    int updateByPrimaryKeySelective(MemberCar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_car
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    int updateByPrimaryKey(MemberCar record);
}