package com.yongjia.dao;

import org.apache.ibatis.annotations.Param;

import com.yongjia.model.MemberSign;

public interface MemberSignMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_sign
     *
     * @mbggenerated Fri Jul 31 22:56:37 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_sign
     *
     * @mbggenerated Fri Jul 31 22:56:37 CST 2015
     */
    int insert(MemberSign record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_sign
     *
     * @mbggenerated Fri Jul 31 22:56:37 CST 2015
     */
    int insertSelective(MemberSign record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_sign
     *
     * @mbggenerated Fri Jul 31 22:56:37 CST 2015
     */
    MemberSign selectByPrimaryKey(Long id);
    
    MemberSign selectByMemberIdAndMonth(@Param("memberId")Long memberId, @Param("month")String month);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_sign
     *
     * @mbggenerated Fri Jul 31 22:56:37 CST 2015
     */
    int updateByPrimaryKeySelective(MemberSign record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_sign
     *
     * @mbggenerated Fri Jul 31 22:56:37 CST 2015
     */
    int updateByPrimaryKey(MemberSign record);
}