package com.yongjia.dao;

import com.yongjia.model.MemberPoint;

public interface MemberPointMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_point
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_point
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    int insert(MemberPoint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_point
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    int insertSelective(MemberPoint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_point
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    MemberPoint selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_point
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    int updateByPrimaryKeySelective(MemberPoint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_point
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    int updateByPrimaryKey(MemberPoint record);
}