package com.yongjia.dao;

import org.apache.ibatis.annotations.Param;

import com.yongjia.model.MemberSignRecord;

public interface MemberSignRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_sign_record
     *
     * @mbggenerated Sun Aug 09 15:22:14 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_sign_record
     *
     * @mbggenerated Sun Aug 09 15:22:14 CST 2015
     */
    int insert(MemberSignRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_sign_record
     *
     * @mbggenerated Sun Aug 09 15:22:14 CST 2015
     */
    int insertSelective(MemberSignRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_sign_record
     *
     * @mbggenerated Sun Aug 09 15:22:14 CST 2015
     */
    MemberSignRecord selectByPrimaryKey(Long id);

    MemberSignRecord selectByMemberIdAndDate(@Param("memberId")Long memberId, @Param("signDate")String signDate);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_sign_record
     *
     * @mbggenerated Sun Aug 09 15:22:14 CST 2015
     */
    int updateByPrimaryKeySelective(MemberSignRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_sign_record
     *
     * @mbggenerated Sun Aug 09 15:22:14 CST 2015
     */
    int updateByPrimaryKey(MemberSignRecord record);
}