package com.yongjia.dao;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.yongjia.model.Message;

public interface MessageMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table wx_msg_item
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    Long deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table wx_msg_item
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    Long insert(Message record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table wx_msg_item
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    Long insertSelective(Message record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table wx_msg_item
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    Message selectByPrimaryKey(Long id);

    /**
     * 
     * @param page
     * @return
     */
    List<Message> selectAll(@Param("page") Map page);

    Long countAll();
    
    /**
     * 
     * @param page
     * @return
     */
    List<Message> selectNews(@Param("page") Map page);

    Long countNews();

    /**
     * 
     * @return
     */
    List<Message> selectManager();
    
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table wx_msg_item
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    Long updateByPrimaryKeySelective(Message record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table wx_msg_item
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    Long updateByPrimaryKeyWithBLOBs(Message record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table wx_msg_item
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    Long updateByPrimaryKey(Message record);
}