package com.yongjia.dao;

import com.yongjia.model.PointPoolConfig;

public interface PointPoolConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table point_pool_config
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table point_pool_config
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    int insert(PointPoolConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table point_pool_config
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    int insertSelective(PointPoolConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table point_pool_config
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    PointPoolConfig selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table point_pool_config
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    int updateByPrimaryKeySelective(PointPoolConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table point_pool_config
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    int updateByPrimaryKey(PointPoolConfig record);
}