package com.yongjia.dao;

import com.yongjia.model.PointPoolRecord;

public interface PointPoolRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table point_pool_record
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table point_pool_record
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    int insert(PointPoolRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table point_pool_record
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    int insertSelective(PointPoolRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table point_pool_record
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    PointPoolRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table point_pool_record
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    int updateByPrimaryKeySelective(PointPoolRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table point_pool_record
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    int updateByPrimaryKey(PointPoolRecord record);
}