package com.yongjia.dao;

import com.yongjia.model.PointPool;

public interface PointPoolMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table point_pool
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table point_pool
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    int insert(PointPool record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table point_pool
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    int insertSelective(PointPool record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table point_pool
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    PointPool selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table point_pool
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    int updateByPrimaryKeySelective(PointPool record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table point_pool
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    int updateByPrimaryKey(PointPool record);
}