package com.yongjia.dao;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.yongjia.model.PointPoolRecord;

public interface PointPoolRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table point_pool_record
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    Long deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table point_pool_record
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    Long insert(PointPoolRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table point_pool_record
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    Long insertSelective(PointPoolRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table point_pool_record
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    PointPoolRecord selectByPrimaryKey(Long id);
    
    List<PointPoolRecord> selectAll(@Param("page")Map page);
    
    Long countAll();
    
    List<PointPoolRecord> selectByPointPoolIdAndType(@Param("pointPoolId")Long pointPoolId,@Param("type")Integer type, @Param("page")Map page);
    
    Long countByPointPoolIdAndType(@Param("pointPoolId")Long pointPoolId,@Param("type")Integer type);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table point_pool_record
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    Long updateByPrimaryKeySelective(PointPoolRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table point_pool_record
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    Long updateByPrimaryKey(PointPoolRecord record);
}