package com.yongjia.dao;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.yongjia.model.PointPool;

public interface PointPoolMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table point_pool
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    Long deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table point_pool
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    Long insert(PointPool record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table point_pool
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    Long insertSelective(PointPool record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table point_pool
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    PointPool selectByPrimaryKey(Long id);

    List<PointPool> selectAll(@Param("page")Map page);
    
    Long countAll();

    Long selectMaxEndAt();

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table point_pool
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    Long updateByPrimaryKeySelective(PointPool record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table point_pool
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    Long updateByPrimaryKey(PointPool record);
}