package com.yongjia.dao;

import com.yongjia.model.Saler;

public interface SalerMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table saler
	 * @mbggenerated  Sun Jun 07 15:16:33 CST 2015
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table saler
	 * @mbggenerated  Sun Jun 07 15:16:33 CST 2015
	 */
	int insert(Saler record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table saler
	 * @mbggenerated  Sun Jun 07 15:16:33 CST 2015
	 */
	int insertSelective(Saler record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table saler
	 * @mbggenerated  Sun Jun 07 15:16:33 CST 2015
	 */
	Saler selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table saler
	 * @mbggenerated  Sun Jun 07 15:16:33 CST 2015
	 */
	int updateByPrimaryKeySelective(Saler record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table saler
	 * @mbggenerated  Sun Jun 07 15:16:33 CST 2015
	 */
	int updateByPrimaryKey(Saler record);
}