package com.yongjia.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.yongjia.model.SignPointConfig;

public interface SignPointConfigMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sign_point_config
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    Long deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sign_point_config
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    Long insert(SignPointConfig record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sign_point_config
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    Long insertSelective(SignPointConfig record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sign_point_config
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    SignPointConfig selectByPrimaryKey(Long id);

    List<SignPointConfig> selectByMonth(String month);

    SignPointConfig selectByMonthAndTimes(@Param("month")String month, @Param("times")Integer times);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sign_point_config
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    Long updateByPrimaryKeySelective(SignPointConfig record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sign_point_config
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    Long updateByPrimaryKey(SignPointConfig record);
}