package com.yongjia.dao;

import com.yongjia.model.SignPointConfig;

public interface SignPointConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign_point_config
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign_point_config
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    int insert(SignPointConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign_point_config
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    int insertSelective(SignPointConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign_point_config
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    SignPointConfig selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign_point_config
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    int updateByPrimaryKeySelective(SignPointConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign_point_config
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    int updateByPrimaryKey(SignPointConfig record);
}