package com.yongjia.dao;

import org.apache.ibatis.annotations.Param;

import com.yongjia.model.SmsSendRecord;

public interface SmsSendRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_send_record
     *
     * @mbggenerated Thu Jul 30 15:41:09 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_send_record
     *
     * @mbggenerated Thu Jul 30 15:41:09 CST 2015
     */
    int insert(SmsSendRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_send_record
     *
     * @mbggenerated Thu Jul 30 15:41:09 CST 2015
     */
    int insertSelective(SmsSendRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_send_record
     *
     * @mbggenerated Thu Jul 30 15:41:09 CST 2015
     */
    SmsSendRecord selectByPrimaryKey(Long id);

    SmsSendRecord selectByMobileAndTpl(@Param("mobile")String mobile, @Param("tpl")String tpl);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_send_record
     *
     * @mbggenerated Thu Jul 30 15:41:09 CST 2015
     */
    int updateByPrimaryKeySelective(SmsSendRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_send_record
     *
     * @mbggenerated Thu Jul 30 15:41:09 CST 2015
     */
    int updateByPrimaryKey(SmsSendRecord record);
}