package com.yongjia.dao;

import com.yongjia.model.User;

public interface UserMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated  Tue Jul 07 14:25:04 CST 2015
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated  Tue Jul 07 14:25:04 CST 2015
	 */
	int insert(User record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated  Tue Jul 07 14:25:04 CST 2015
	 */
	int insertSelective(User record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated  Tue Jul 07 14:25:04 CST 2015
	 */
	User selectByPrimaryKey(Integer id);
	
	/**
	 * 
	 * @param account
	 * @return
	 */
	User selectByAccount(String account);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated  Tue Jul 07 14:25:04 CST 2015
	 */
	int updateByPrimaryKeySelective(User record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated  Tue Jul 07 14:25:04 CST 2015
	 */
	int updateByPrimaryKey(User record);
}