package com.yongjia.dao;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.yongjia.model.User;

public interface UserMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated  Tue Jul 07 14:25:04 CST 2015
	 */
    Long deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated  Tue Jul 07 14:25:04 CST 2015
	 */
	Long insert(User record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated  Tue Jul 07 14:25:04 CST 2015
	 */
	Long insertSelective(User record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated  Tue Jul 07 14:25:04 CST 2015
	 */
	User selectByPrimaryKey(Long id);
	
	List<User> selectByNameAndPhone(@Param("name")String name, @Param("mobile")String mobile, @Param("page")Map page);
	
	Long countByNameAndPhone(@Param("name")String name, @Param("mobile")String mobile);
	/**
	 * 
	 * @param account
	 * @return
	 */
	User selectByAccount(String account);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated  Tue Jul 07 14:25:04 CST 2015
	 */
	Long updateByPrimaryKeySelective(User record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated  Tue Jul 07 14:25:04 CST 2015
	 */
	Long updateByPrimaryKey(User record);
}