package com.yongjia.dao;

import com.yongjia.model.WxMessage;

public interface WxMessageMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table wx_message
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    Long deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table wx_message
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    Long insert(WxMessage record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table wx_message
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    Long insertSelective(WxMessage record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table wx_message
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    WxMessage selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table wx_message
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    Long updateByPrimaryKeySelective(WxMessage record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table wx_message
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    Long updateByPrimaryKey(WxMessage record);
}