package com.yongjia.dao;

import com.yongjia.model.WxMessage;

public interface WxMessageMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wx_message
	 * @mbggenerated  Sun Jun 14 20:57:12 CST 2015
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wx_message
	 * @mbggenerated  Sun Jun 14 20:57:12 CST 2015
	 */
	int insert(WxMessage record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wx_message
	 * @mbggenerated  Sun Jun 14 20:57:12 CST 2015
	 */
	int insertSelective(WxMessage record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wx_message
	 * @mbggenerated  Sun Jun 14 20:57:12 CST 2015
	 */
	WxMessage selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wx_message
	 * @mbggenerated  Sun Jun 14 20:57:12 CST 2015
	 */
	int updateByPrimaryKeySelective(WxMessage record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wx_message
	 * @mbggenerated  Sun Jun 14 20:57:12 CST 2015
	 */
	int updateByPrimaryKey(WxMessage record);
}