package com.yongjia.dao;

import com.yongjia.model.WxRuleKeyword;

public interface WxRuleKeywordMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wx_rule_keyword
	 * @mbggenerated  Tue Jul 07 14:25:04 CST 2015
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wx_rule_keyword
	 * @mbggenerated  Tue Jul 07 14:25:04 CST 2015
	 */
	int insert(WxRuleKeyword record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wx_rule_keyword
	 * @mbggenerated  Tue Jul 07 14:25:04 CST 2015
	 */
	int insertSelective(WxRuleKeyword record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wx_rule_keyword
	 * @mbggenerated  Tue Jul 07 14:25:04 CST 2015
	 */
    WxRuleKeyword selectByPrimaryKey(Integer id);
    /**
     * 
     * @param keyword
     * @return
     */
    WxRuleKeyword selectByKeyword(String keyword);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wx_rule_keyword
	 * @mbggenerated  Tue Jul 07 14:25:04 CST 2015
	 */
	int updateByPrimaryKeySelective(WxRuleKeyword record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wx_rule_keyword
	 * @mbggenerated  Tue Jul 07 14:25:04 CST 2015
	 */
	int updateByPrimaryKey(WxRuleKeyword record);
}