package com.yongjia.dao;

import com.yongjia.model.WxRuleKeyword;

public interface WxRuleKeywordMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wx_rule_keyword
	 * @mbggenerated  Tue Jul 07 14:25:04 CST 2015
	 */
    Long deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wx_rule_keyword
	 * @mbggenerated  Tue Jul 07 14:25:04 CST 2015
	 */
    Long insert(WxRuleKeyword record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wx_rule_keyword
	 * @mbggenerated  Tue Jul 07 14:25:04 CST 2015
	 */
    Long insertSelective(WxRuleKeyword record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wx_rule_keyword
	 * @mbggenerated  Tue Jul 07 14:25:04 CST 2015
	 */
    WxRuleKeyword selectByPrimaryKey(Long id);
    /**
     * 
     * @param keyword
     * @return
     */
    WxRuleKeyword selectByKeyword(String keyword);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wx_rule_keyword
	 * @mbggenerated  Tue Jul 07 14:25:04 CST 2015
	 */
    Long updateByPrimaryKeySelective(WxRuleKeyword record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wx_rule_keyword
	 * @mbggenerated  Tue Jul 07 14:25:04 CST 2015
	 */
    Long updateByPrimaryKey(WxRuleKeyword record);
}