package com.yongjia.dao;

import com.yongjia.model.WxRule;

public interface WxRuleMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wx_rule
	 * @mbggenerated  Tue Jul 07 14:25:04 CST 2015
	 */
    Long deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wx_rule
	 * @mbggenerated  Tue Jul 07 14:25:04 CST 2015
	 */
    Long insert(WxRule record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wx_rule
	 * @mbggenerated  Tue Jul 07 14:25:04 CST 2015
	 */
    Long insertSelective(WxRule record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wx_rule
	 * @mbggenerated  Tue Jul 07 14:25:04 CST 2015
	 */
	WxRule selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wx_rule
	 * @mbggenerated  Tue Jul 07 14:25:04 CST 2015
	 */
	Long updateByPrimaryKeySelective(WxRule record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wx_rule
	 * @mbggenerated  Tue Jul 07 14:25:04 CST 2015
	 */
	Long updateByPrimaryKey(WxRule record);
}