package com.yongjia.dao;

import com.yongjia.model.WxRuleKeyword;

public interface WxRuleKeywordMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wx_rule_keyword
	 * @mbggenerated  Sun Jun 14 20:57:12 CST 2015
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wx_rule_keyword
	 * @mbggenerated  Sun Jun 14 20:57:12 CST 2015
	 */
	int insert(WxRuleKeyword record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wx_rule_keyword
	 * @mbggenerated  Sun Jun 14 20:57:12 CST 2015
	 */
	int insertSelective(WxRuleKeyword record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table wx_rule_keyword
     * @mbggenerated  Sun Jun 14 20:57:12 CST 2015
     */
    WxRuleKeyword selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table wx_rule_keyword
     * @mbggenerated  Sun Jun 14 20:57:12 CST 2015
     */
    WxRuleKeyword selectByKeyword(String keyword);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wx_rule_keyword
	 * @mbggenerated  Sun Jun 14 20:57:12 CST 2015
	 */
	int updateByPrimaryKeySelective(WxRuleKeyword record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wx_rule_keyword
	 * @mbggenerated  Sun Jun 14 20:57:12 CST 2015
	 */
	int updateByPrimaryKey(WxRuleKeyword record);
}