package com.yongjia.dao;

import com.yongjia.model.WxUser;

public interface WxUserMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wx_user
	 * @mbggenerated  Sun Jun 14 20:37:53 CST 2015
	 */
	int deleteByPrimaryKey(String openid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wx_user
	 * @mbggenerated  Sun Jun 14 20:37:53 CST 2015
	 */
	int insert(WxUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wx_user
	 * @mbggenerated  Sun Jun 14 20:37:53 CST 2015
	 */
	int insertSelective(WxUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wx_user
	 * @mbggenerated  Sun Jun 14 20:37:53 CST 2015
	 */
	WxUser selectByPrimaryKey(String openid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wx_user
	 * @mbggenerated  Sun Jun 14 20:37:53 CST 2015
	 */
	int updateByPrimaryKeySelective(WxUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wx_user
	 * @mbggenerated  Sun Jun 14 20:37:53 CST 2015
	 */
	int updateByPrimaryKey(WxUser record);
}