package com.yongjia.model;

public class AppointmentAndMember {
    // 维修，保养，看车，年审，其他
    public static final int TypeWeixiu = 1;
    public static final int TypeBaoyang = 2;
    public static final int TypeKanche = 3;
    public static final int TypeNianshen = 4;
    public static final int TypeQita = 5;

    public static final int StatusToConfirm = 0;
    public static final int StatusToDo = 1;
    public static final int StatusFinish = 2;
    public static final int StatusCancel = 3;

    public static final int TestCar = 1;
    public static final int NotTestCar = 2;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column appointment.id
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private Long id;
    
    private Long memberId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column appointment.type
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column appointment.car_type
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private String carType;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * appointment.connect_phone
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private String connectPhone;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * appointment.problem_desc
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private String problemDesc;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column appointment.kilo
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private String kilo;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * appointment.is_test_drive
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private Integer isTestDrive;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * appointment.appoint_time
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private Long appointTime;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * appointment.arrive_time
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private Long arriveTime;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column appointment.status
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * appointment.create_at
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private Long createAt;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * appointment.create_by
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private Long createBy;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * appointment.update_at
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private Long updateAt;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * appointment.update_by
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private Long updateBy;
    
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.mobile
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.sex
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private Integer sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.head_imgurl
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private String headImgurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.status
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private Integer memberStatus;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * appointment.appoint_content
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private String appointContent;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * appointment.id
     * 
     * @return the value of appointment.id
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column appointment.id
     * 
     * @param id the value for appointment.id
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    public Long getMemberId() {
        return memberId;
    }

    public void setMemberId(Long memberId) {
        this.memberId = memberId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getMobile() {
        return mobile;
    }

    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    public Integer getSex() {
        return sex;
    }

    public void setSex(Integer sex) {
        this.sex = sex;
    }

    public String getHeadImgurl() {
        return headImgurl;
    }

    public void setHeadImgurl(String headImgurl) {
        this.headImgurl = headImgurl;
    }

    public Integer getMemberStatus() {
        return memberStatus;
    }

    public void setMemberStatus(Integer memberStatus) {
        this.memberStatus = memberStatus;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * appointment.type
     * 
     * @return the value of appointment.type
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * appointment.type
     * 
     * @param type the value for appointment.type
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * appointment.car_type
     * 
     * @return the value of appointment.car_type
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public String getCarType() {
        return carType;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * appointment.car_type
     * 
     * @param carType the value for appointment.car_type
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setCarType(String carType) {
        this.carType = carType;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * appointment.connect_phone
     * 
     * @return the value of appointment.connect_phone
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public String getConnectPhone() {
        return connectPhone;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * appointment.connect_phone
     * 
     * @param connectPhone the value for appointment.connect_phone
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setConnectPhone(String connectPhone) {
        this.connectPhone = connectPhone;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * appointment.problem_desc
     * 
     * @return the value of appointment.problem_desc
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public String getProblemDesc() {
        return problemDesc;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * appointment.problem_desc
     * 
     * @param problemDesc the value for appointment.problem_desc
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setProblemDesc(String problemDesc) {
        this.problemDesc = problemDesc;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * appointment.kilo
     * 
     * @return the value of appointment.kilo
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public String getKilo() {
        return kilo;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * appointment.kilo
     * 
     * @param kilo the value for appointment.kilo
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setKilo(String kilo) {
        this.kilo = kilo;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * appointment.is_test_drive
     * 
     * @return the value of appointment.is_test_drive
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public Integer getIsTestDrive() {
        return isTestDrive;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * appointment.is_test_drive
     * 
     * @param isTestDrive the value for appointment.is_test_drive
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setIsTestDrive(Integer isTestDrive) {
        this.isTestDrive = isTestDrive;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * appointment.appoint_time
     * 
     * @return the value of appointment.appoint_time
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public Long getAppointTime() {
        return appointTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * appointment.appoint_time
     * 
     * @param appointTime the value for appointment.appoint_time
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setAppointTime(Long appointTime) {
        this.appointTime = appointTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * appointment.arrive_time
     * 
     * @return the value of appointment.arrive_time
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public Long getArriveTime() {
        return arriveTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * appointment.arrive_time
     * 
     * @param arriveTime the value for appointment.arrive_time
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setArriveTime(Long arriveTime) {
        this.arriveTime = arriveTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * appointment.status
     * 
     * @return the value of appointment.status
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * appointment.status
     * 
     * @param status the value for appointment.status
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * appointment.create_at
     * 
     * @return the value of appointment.create_at
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public Long getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * appointment.create_at
     * 
     * @param createAt the value for appointment.create_at
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setCreateAt(Long createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * appointment.create_by
     * 
     * @return the value of appointment.create_by
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public Long getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * appointment.create_by
     * 
     * @param createBy the value for appointment.create_by
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setCreateBy(Long createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * appointment.update_at
     * 
     * @return the value of appointment.update_at
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public Long getUpdateAt() {
        return updateAt;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * appointment.update_at
     * 
     * @param updateAt the value for appointment.update_at
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setUpdateAt(Long updateAt) {
        this.updateAt = updateAt;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * appointment.update_by
     * 
     * @return the value of appointment.update_by
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public Long getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * appointment.update_by
     * 
     * @param updateBy the value for appointment.update_by
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setUpdateBy(Long updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * appointment.appoint_content
     * 
     * @return the value of appointment.appoint_content
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public String getAppointContent() {
        return appointContent;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * appointment.appoint_content
     * 
     * @param appointContent the value for appointment.appoint_content
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setAppointContent(String appointContent) {
        this.appointContent = appointContent;
    }
}