package com.yongjia.model;

public class CarHallPic {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_hall_pic.id
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_hall_pic.car_hall_id
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private Long carHallId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_hall_pic.img
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private String img;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_hall_pic.id
     *
     * @return the value of car_hall_pic.id
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_hall_pic.id
     *
     * @param id the value for car_hall_pic.id
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_hall_pic.car_hall_id
     *
     * @return the value of car_hall_pic.car_hall_id
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public Long getCarHallId() {
        return carHallId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_hall_pic.car_hall_id
     *
     * @param carHallId the value for car_hall_pic.car_hall_id
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setCarHallId(Long carHallId) {
        this.carHallId = carHallId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_hall_pic.img
     *
     * @return the value of car_hall_pic.img
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public String getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_hall_pic.img
     *
     * @param img the value for car_hall_pic.img
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setImg(String img) {
        this.img = img;
    }
}