package com.yongjia.model;

public class CarHallModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_hall_model.id
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_hall_model.car_hall_id
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private Integer carHallId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_hall_model.car_model_id
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private Integer carModelId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_hall_model.id
     *
     * @return the value of car_hall_model.id
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_hall_model.id
     *
     * @param id the value for car_hall_model.id
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_hall_model.car_hall_id
     *
     * @return the value of car_hall_model.car_hall_id
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public Integer getCarHallId() {
        return carHallId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_hall_model.car_hall_id
     *
     * @param carHallId the value for car_hall_model.car_hall_id
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setCarHallId(Integer carHallId) {
        this.carHallId = carHallId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_hall_model.car_model_id
     *
     * @return the value of car_hall_model.car_model_id
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public Integer getCarModelId() {
        return carModelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_hall_model.car_model_id
     *
     * @param carModelId the value for car_hall_model.car_model_id
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setCarModelId(Integer carModelId) {
        this.carModelId = carModelId;
    }
}