package com.yongjia.model;

import java.util.List;

public class CarHall {
    public static final int StatusStop = 1;
    public static final int StatusActive = 0;

    public static final int ImportChina = 0;
    public static final int ImportForeign = 1;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column car_hall.id
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private Long id;

    private Long typeId;

    private String typeName;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column car_hall.import_flag
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private Integer importFlag;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * car_hall.price_lowest
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private String priceLowest;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column car_hall.price_most
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private String priceMost;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column car_hall.img
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private String img;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column car_hall.status
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column car_hall.create_at
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private Long createAt;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column car_hall.create_by
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private Long createBy;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column car_hall.update_at
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private Long updateAt;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column car_hall.update_by
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private Long updateBy;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column car_hall.id
     * 
     * @return the value of car_hall.id
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    
    
    private List<String> carHallPics;
    
    private List<Long> carModelIds;
    
    private Integer carModelCount;
    
    public Integer getCarModelCount() {
        return carModelCount;
    }

    public void setCarModelCount(Integer carModelCount) {
        this.carModelCount = carModelCount;
    }

    public List<String> getCarHallPics() {
        return carHallPics;
    }

    public void setCarHallPics(List<String> carHallPics) {
        this.carHallPics = carHallPics;
    }

    public List<Long> getCarModelIds() {
        return carModelIds;
    }

    public void setCarModelIds(List<Long> carModelIds) {
        this.carModelIds = carModelIds;
    }

    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column car_hall.id
     * 
     * @param id the value for car_hall.id
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    public Long getTypeId() {
        return typeId;
    }

    public void setTypeId(Long typeId) {
        this.typeId = typeId;
    }

    public String getTypeName() {
        return typeName;
    }

    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * car_hall.import_flag
     * 
     * @return the value of car_hall.import_flag
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public Integer getImportFlag() {
        return importFlag;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * car_hall.import_flag
     * 
     * @param importFlag the value for car_hall.import_flag
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setImportFlag(Integer importFlag) {
        this.importFlag = importFlag;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * car_hall.price_lowest
     * 
     * @return the value of car_hall.price_lowest
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public String getPriceLowest() {
        return priceLowest;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * car_hall.price_lowest
     * 
     * @param priceLowest the value for car_hall.price_lowest
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setPriceLowest(String priceLowest) {
        this.priceLowest = priceLowest;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * car_hall.price_most
     * 
     * @return the value of car_hall.price_most
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public String getPriceMost() {
        return priceMost;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * car_hall.price_most
     * 
     * @param priceMost the value for car_hall.price_most
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setPriceMost(String priceMost) {
        this.priceMost = priceMost;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column car_hall.img
     * 
     * @return the value of car_hall.img
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public String getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column car_hall.img
     * 
     * @param img the value for car_hall.img
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setImg(String img) {
        this.img = img;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * car_hall.status
     * 
     * @return the value of car_hall.status
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column car_hall.status
     * 
     * @param status the value for car_hall.status
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * car_hall.create_at
     * 
     * @return the value of car_hall.create_at
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public Long getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * car_hall.create_at
     * 
     * @param createAt the value for car_hall.create_at
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setCreateAt(Long createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * car_hall.create_by
     * 
     * @return the value of car_hall.create_by
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public Long getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * car_hall.create_by
     * 
     * @param createBy the value for car_hall.create_by
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setCreateBy(Long createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * car_hall.update_at
     * 
     * @return the value of car_hall.update_at
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public Long getUpdateAt() {
        return updateAt;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * car_hall.update_at
     * 
     * @param updateAt the value for car_hall.update_at
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setUpdateAt(Long updateAt) {
        this.updateAt = updateAt;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * car_hall.update_by
     * 
     * @return the value of car_hall.update_by
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public Long getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * car_hall.update_by
     * 
     * @param updateBy the value for car_hall.update_by
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setUpdateBy(Long updateBy) {
        this.updateBy = updateBy;
    }
}