package com.yongjia.model;

public class CarModel {
    public static final int StatusStop = 1;
    public static final int StatusActive = 0;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_model.id
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_model.type_id
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private Long typeId;
    private String typeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_model.car_model_name
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private String carModelName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_model.status
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_model.id
     *
     * @return the value of car_model.id
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_model.id
     *
     * @param id the value for car_model.id
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_model.type_id
     *
     * @return the value of car_model.type_id
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public Long getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_model.type_id
     *
     * @param typeId the value for car_model.type_id
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setTypeId(Long typeId) {
        this.typeId = typeId;
    }

    public String getTypeName() {
        return typeName;
    }

    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_model.car_model_name
     *
     * @return the value of car_model.car_model_name
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public String getCarModelName() {
        return carModelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_model.car_model_name
     *
     * @param carModelName the value for car_model.car_model_name
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setCarModelName(String carModelName) {
        this.carModelName = carModelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_model.status
     *
     * @return the value of car_model.status
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_model.status
     *
     * @param status the value for car_model.status
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}