package com.yongjia.model;

public class CarModelParam {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_model_param.id
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_model_param.car_model_id
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private Integer carModelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_model_param.param_name
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private String paramName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_model_param.param_value
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private String paramValue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_model_param.id
     *
     * @return the value of car_model_param.id
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_model_param.id
     *
     * @param id the value for car_model_param.id
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_model_param.car_model_id
     *
     * @return the value of car_model_param.car_model_id
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public Integer getCarModelId() {
        return carModelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_model_param.car_model_id
     *
     * @param carModelId the value for car_model_param.car_model_id
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setCarModelId(Integer carModelId) {
        this.carModelId = carModelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_model_param.param_name
     *
     * @return the value of car_model_param.param_name
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public String getParamName() {
        return paramName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_model_param.param_name
     *
     * @param paramName the value for car_model_param.param_name
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setParamName(String paramName) {
        this.paramName = paramName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_model_param.param_value
     *
     * @return the value of car_model_param.param_value
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public String getParamValue() {
        return paramValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_model_param.param_value
     *
     * @param paramValue the value for car_model_param.param_value
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setParamValue(String paramValue) {
        this.paramValue = paramValue;
    }
}