package com.yongjia.model;

public class CarType {

    public static final int ImportChina = 0;
    public static final int ImportForeign = 1;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_type.id
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_type.car_type_name
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private String carTypeName;
    
    private Integer importFlag;
    

    public Integer getImportFlag() {
        return importFlag;
    }

    public void setImportFlag(Integer importFlag) {
        this.importFlag = importFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_type.id
     *
     * @return the value of car_type.id
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_type.id
     *
     * @param id the value for car_type.id
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_type.car_type_name
     *
     * @return the value of car_type.car_type_name
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public String getCarTypeName() {
        return carTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_type.car_type_name
     *
     * @param carTypeName the value for car_type.car_type_name
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setCarTypeName(String carTypeName) {
        this.carTypeName = carTypeName;
    }
}