package com.yongjia.model;

public class Gift {
    
    public static final int StatusPubnish = 1;
    public static final int StatusStop = 0;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gift.id
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gift.name
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gift.pic
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private String pic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gift.privider_name
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private String prividerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gift.status
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gift.point
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private Integer point;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gift.create_at
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private Long createAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gift.create_by
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private Long createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gift.update_at
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private Long updateAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gift.update_by
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private Long updateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gift.content
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gift.id
     *
     * @return the value of gift.id
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gift.id
     *
     * @param id the value for gift.id
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gift.name
     *
     * @return the value of gift.name
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gift.name
     *
     * @param name the value for gift.name
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gift.pic
     *
     * @return the value of gift.pic
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public String getPic() {
        return pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gift.pic
     *
     * @param pic the value for gift.pic
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setPic(String pic) {
        this.pic = pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gift.privider_name
     *
     * @return the value of gift.privider_name
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public String getPrividerName() {
        return prividerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gift.privider_name
     *
     * @param prividerName the value for gift.privider_name
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setPrividerName(String prividerName) {
        this.prividerName = prividerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gift.status
     *
     * @return the value of gift.status
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gift.status
     *
     * @param status the value for gift.status
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gift.point
     *
     * @return the value of gift.point
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public Integer getPoint() {
        return point;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gift.point
     *
     * @param point the value for gift.point
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setPoint(Integer point) {
        this.point = point;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gift.create_at
     *
     * @return the value of gift.create_at
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public Long getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gift.create_at
     *
     * @param createAt the value for gift.create_at
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setCreateAt(Long createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gift.create_by
     *
     * @return the value of gift.create_by
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public Long getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gift.create_by
     *
     * @param createBy the value for gift.create_by
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setCreateBy(Long createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gift.update_at
     *
     * @return the value of gift.update_at
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public Long getUpdateAt() {
        return updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gift.update_at
     *
     * @param updateAt the value for gift.update_at
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setUpdateAt(Long updateAt) {
        this.updateAt = updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gift.update_by
     *
     * @return the value of gift.update_by
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public Long getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gift.update_by
     *
     * @param updateBy the value for gift.update_by
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setUpdateBy(Long updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gift.content
     *
     * @return the value of gift.content
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gift.content
     *
     * @param content the value for gift.content
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setContent(String content) {
        this.content = content;
    }
}