package com.yongjia.model;

public class GiftPic {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gift_pic.id
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gift_pic.gift_id
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private Integer giftId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gift_pic.pic
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private String pic;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gift_pic.id
     *
     * @return the value of gift_pic.id
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gift_pic.id
     *
     * @param id the value for gift_pic.id
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gift_pic.gift_id
     *
     * @return the value of gift_pic.gift_id
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public Integer getGiftId() {
        return giftId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gift_pic.gift_id
     *
     * @param giftId the value for gift_pic.gift_id
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setGiftId(Integer giftId) {
        this.giftId = giftId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gift_pic.pic
     *
     * @return the value of gift_pic.pic
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public String getPic() {
        return pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gift_pic.pic
     *
     * @param pic the value for gift_pic.pic
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setPic(String pic) {
        this.pic = pic;
    }
}