package com.yongjia.model;

public class MemberSign {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_sign.id
     *
     * @mbggenerated Fri Jul 31 22:56:37 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_sign.member_id
     *
     * @mbggenerated Fri Jul 31 22:56:37 CST 2015
     */
    private Long memberId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_sign.month
     *
     * @mbggenerated Fri Jul 31 22:56:37 CST 2015
     */
    private String month;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_sign.times
     *
     * @mbggenerated Fri Jul 31 22:56:37 CST 2015
     */
    private Integer times;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_sign.id
     *
     * @return the value of member_sign.id
     *
     * @mbggenerated Fri Jul 31 22:56:37 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_sign.id
     *
     * @param id the value for member_sign.id
     *
     * @mbggenerated Fri Jul 31 22:56:37 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_sign.member_id
     *
     * @return the value of member_sign.member_id
     *
     * @mbggenerated Fri Jul 31 22:56:37 CST 2015
     */
    public Long getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_sign.member_id
     *
     * @param memberId the value for member_sign.member_id
     *
     * @mbggenerated Fri Jul 31 22:56:37 CST 2015
     */
    public void setMemberId(Long memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_sign.month
     *
     * @return the value of member_sign.month
     *
     * @mbggenerated Fri Jul 31 22:56:37 CST 2015
     */
    public String getMonth() {
        return month;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_sign.month
     *
     * @param month the value for member_sign.month
     *
     * @mbggenerated Fri Jul 31 22:56:37 CST 2015
     */
    public void setMonth(String month) {
        this.month = month;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_sign.times
     *
     * @return the value of member_sign.times
     *
     * @mbggenerated Fri Jul 31 22:56:37 CST 2015
     */
    public Integer getTimes() {
        return times;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_sign.times
     *
     * @param times the value for member_sign.times
     *
     * @mbggenerated Fri Jul 31 22:56:37 CST 2015
     */
    public void setTimes(Integer times) {
        this.times = times;
    }
}