package com.yongjia.model;

public class MemberPoint {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_point.id
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_point.member_id
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private Integer memberId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_point.point_pool_id
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private Integer pointPoolId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_point.point
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private Integer point;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_point.id
     *
     * @return the value of member_point.id
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_point.id
     *
     * @param id the value for member_point.id
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_point.member_id
     *
     * @return the value of member_point.member_id
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public Integer getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_point.member_id
     *
     * @param memberId the value for member_point.member_id
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setMemberId(Integer memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_point.point_pool_id
     *
     * @return the value of member_point.point_pool_id
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public Integer getPointPoolId() {
        return pointPoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_point.point_pool_id
     *
     * @param pointPoolId the value for member_point.point_pool_id
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setPointPoolId(Integer pointPoolId) {
        this.pointPoolId = pointPoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_point.point
     *
     * @return the value of member_point.point
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public Integer getPoint() {
        return point;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_point.point
     *
     * @param point the value for member_point.point
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setPoint(Integer point) {
        this.point = point;
    }
}