package com.yongjia.model;

public class Member {
    
    public static final int StatusMember = 1;
    public static final int StatusCarOwner = 2;
    
    public static final int ToVali = 1;
    public static final int NoVali = 0;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.id
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.name
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.mobile
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.sex
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private Integer sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.head_imgurl
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private String headImgurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.status
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.status
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private Integer valiFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.create_at
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private Long createAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.create_by
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private Long createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.update_at
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private Long updateAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.update_by
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private Long updateBy;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.id
     *
     * @return the value of member.id
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.id
     *
     * @param id the value for member.id
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.name
     *
     * @return the value of member.name
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.name
     *
     * @param name the value for member.name
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.mobile
     *
     * @return the value of member.mobile
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.mobile
     *
     * @param mobile the value for member.mobile
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.sex
     *
     * @return the value of member.sex
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.sex
     *
     * @param sex the value for member.sex
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.head_imgurl
     *
     * @return the value of member.head_imgurl
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public String getHeadImgurl() {
        return headImgurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.head_imgurl
     *
     * @param headImgurl the value for member.head_imgurl
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setHeadImgurl(String headImgurl) {
        this.headImgurl = headImgurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.status
     *
     * @return the value of member.status
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.status
     *
     * @param status the value for member.status
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    public Integer getValiFlag() {
        return valiFlag;
    }

    public void setValiFlag(Integer valiFlag) {
        this.valiFlag = valiFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.create_at
     *
     * @return the value of member.create_at
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public Long getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.create_at
     *
     * @param createAt the value for member.create_at
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setCreateAt(Long createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.create_by
     *
     * @return the value of member.create_by
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public Long getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.create_by
     *
     * @param createBy the value for member.create_by
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setCreateBy(Long createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.update_at
     *
     * @return the value of member.update_at
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public Long getUpdateAt() {
        return updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.update_at
     *
     * @param updateAt the value for member.update_at
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setUpdateAt(Long updateAt) {
        this.updateAt = updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.update_by
     *
     * @return the value of member.update_by
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public Long getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.update_by
     *
     * @param updateBy the value for member.update_by
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setUpdateBy(Long updateBy) {
        this.updateBy = updateBy;
    }
}