package com.yongjia.model;

public class MemberPointRecord {
    
    public static final int TypeGet = 0;
    public static final int TypeUse = 1;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_point_record.id
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_point_record.member_id
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private Long memberId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_point_record.point_pool_id
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private Long pointPoolId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_point_record.point
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private Integer point;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_point_record.type
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_point_record.action
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private String action;
    private String actionContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_point_record.create_at
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private Long createAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_point_record.create_by
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private Long createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_point_record.remark
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private String remark;

    public String getActionContent() {
        return actionContent;
    }

    public void setActionContent(String actionContent) {
        this.actionContent = actionContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_point_record.id
     *
     * @return the value of member_point_record.id
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_point_record.id
     *
     * @param id the value for member_point_record.id
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_point_record.member_id
     *
     * @return the value of member_point_record.member_id
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public Long getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_point_record.member_id
     *
     * @param memberId the value for member_point_record.member_id
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setMemberId(Long memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_point_record.point_pool_id
     *
     * @return the value of member_point_record.point_pool_id
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public Long getPointPoolId() {
        return pointPoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_point_record.point_pool_id
     *
     * @param pointPoolId the value for member_point_record.point_pool_id
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setPointPoolId(Long pointPoolId) {
        this.pointPoolId = pointPoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_point_record.point
     *
     * @return the value of member_point_record.point
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public Integer getPoint() {
        return point;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_point_record.point
     *
     * @param point the value for member_point_record.point
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setPoint(Integer point) {
        this.point = point;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_point_record.type
     *
     * @return the value of member_point_record.type
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_point_record.type
     *
     * @param type the value for member_point_record.type
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_point_record.action
     *
     * @return the value of member_point_record.action
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public String getAction() {
        return action;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_point_record.action
     *
     * @param action the value for member_point_record.action
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setAction(String action) {
        this.action = action;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_point_record.create_at
     *
     * @return the value of member_point_record.create_at
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public Long getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_point_record.create_at
     *
     * @param createAt the value for member_point_record.create_at
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setCreateAt(Long createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_point_record.create_by
     *
     * @return the value of member_point_record.create_by
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public Long getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_point_record.create_by
     *
     * @param createBy the value for member_point_record.create_by
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setCreateBy(Long createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_point_record.remark
     *
     * @return the value of member_point_record.remark
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_point_record.remark
     *
     * @param remark the value for member_point_record.remark
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }
}