package com.yongjia.model;

public class MemberCar {
    
    public static final int StatusToVali = 0;
    public static final int StatusYes = 1;
    public static final int StatusNo = 2;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_car.id
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_car.member_id
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private Long memberId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_car.type_name
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private String typeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_car.model_name
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private String modelName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_car.vin_no
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private String vinNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_car.car_number
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private String carNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_car.status
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_car.create_at
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private Long createAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_car.create_by
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private Long createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_car.update_at
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private Long updateAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_car.update_by
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private Long updateBy;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_car.id
     *
     * @return the value of member_car.id
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_car.id
     *
     * @param id the value for member_car.id
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_car.member_id
     *
     * @return the value of member_car.member_id
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public Long getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_car.member_id
     *
     * @param memberId the value for member_car.member_id
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setMemberId(Long memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_car.type_name
     *
     * @return the value of member_car.type_name
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_car.type_name
     *
     * @param typeName the value for member_car.type_name
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_car.model_name
     *
     * @return the value of member_car.model_name
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public String getModelName() {
        return modelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_car.model_name
     *
     * @param modelName the value for member_car.model_name
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setModelName(String modelName) {
        this.modelName = modelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_car.vin_no
     *
     * @return the value of member_car.vin_no
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public String getVinNo() {
        return vinNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_car.vin_no
     *
     * @param vinNo the value for member_car.vin_no
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setVinNo(String vinNo) {
        this.vinNo = vinNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_car.car_number
     *
     * @return the value of member_car.car_number
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public String getCarNumber() {
        return carNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_car.car_number
     *
     * @param carNumber the value for member_car.car_number
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setCarNumber(String carNumber) {
        this.carNumber = carNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_car.status
     *
     * @return the value of member_car.status
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_car.status
     *
     * @param status the value for member_car.status
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_car.create_at
     *
     * @return the value of member_car.create_at
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public Long getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_car.create_at
     *
     * @param createAt the value for member_car.create_at
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setCreateAt(Long createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_car.create_by
     *
     * @return the value of member_car.create_by
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public Long getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_car.create_by
     *
     * @param createBy the value for member_car.create_by
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setCreateBy(Long createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_car.update_at
     *
     * @return the value of member_car.update_at
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public Long getUpdateAt() {
        return updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_car.update_at
     *
     * @param updateAt the value for member_car.update_at
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setUpdateAt(Long updateAt) {
        this.updateAt = updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_car.update_by
     *
     * @return the value of member_car.update_by
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public Long getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_car.update_by
     *
     * @param updateBy the value for member_car.update_by
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setUpdateBy(Long updateBy) {
        this.updateBy = updateBy;
    }
}