package com.yongjia.model;

public class PointPoolRecord {
    
    public static final int TypeReduce = 0;
    public static final int TypeAdd = 1;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column point_pool_record.id
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column point_pool_record.point_pool_id
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private Long pointPoolId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column point_pool_record.operator_role
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private String operatorRole;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column point_pool_record.operator_name
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private String operatorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column point_pool_record.action
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private String action;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column point_pool_record.point
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private Integer type;
    private Integer point;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column point_pool_record.total_point_before
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private Integer totalPointBefore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column point_pool_record.total_point_after
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private Integer totalPointAfter;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column point_pool_record.id
     *
     * @return the value of point_pool_record.id
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column point_pool_record.id
     *
     * @param id the value for point_pool_record.id
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column point_pool_record.point_pool_id
     *
     * @return the value of point_pool_record.point_pool_id
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public Long getPointPoolId() {
        return pointPoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column point_pool_record.point_pool_id
     *
     * @param pointPoolId the value for point_pool_record.point_pool_id
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setPointPoolId(Long pointPoolId) {
        this.pointPoolId = pointPoolId;
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column point_pool_record.operator_role
     *
     * @return the value of point_pool_record.operator_role
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public String getOperatorRole() {
        return operatorRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column point_pool_record.operator_role
     *
     * @param operatorRole the value for point_pool_record.operator_role
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setOperatorRole(String operatorRole) {
        this.operatorRole = operatorRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column point_pool_record.operator_name
     *
     * @return the value of point_pool_record.operator_name
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public String getOperatorName() {
        return operatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column point_pool_record.operator_name
     *
     * @param operatorName the value for point_pool_record.operator_name
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setOperatorName(String operatorName) {
        this.operatorName = operatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column point_pool_record.action
     *
     * @return the value of point_pool_record.action
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public String getAction() {
        return action;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column point_pool_record.action
     *
     * @param action the value for point_pool_record.action
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setAction(String action) {
        this.action = action;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column point_pool_record.point
     *
     * @return the value of point_pool_record.point
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public Integer getPoint() {
        return point;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column point_pool_record.point
     *
     * @param point the value for point_pool_record.point
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setPoint(Integer point) {
        this.point = point;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column point_pool_record.total_point_before
     *
     * @return the value of point_pool_record.total_point_before
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public Integer getTotalPointBefore() {
        return totalPointBefore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column point_pool_record.total_point_before
     *
     * @param totalPointBefore the value for point_pool_record.total_point_before
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setTotalPointBefore(Integer totalPointBefore) {
        this.totalPointBefore = totalPointBefore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column point_pool_record.total_point_after
     *
     * @return the value of point_pool_record.total_point_after
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public Integer getTotalPointAfter() {
        return totalPointAfter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column point_pool_record.total_point_after
     *
     * @param totalPointAfter the value for point_pool_record.total_point_after
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setTotalPointAfter(Integer totalPointAfter) {
        this.totalPointAfter = totalPointAfter;
    }
}