package com.yongjia.model;

public class PotentialCustomer {

    public static final int PayTypeMoney = 0;
    public static final int PayTypeCash = 1;
    
    public static final int BuyTypeFirst = 0;
    public static final int BuyTypeAdd = 1;
    public static final int BuyTypeExchange = 2;
    
    public static final int BuyForHome = 0;
    public static final int BuyForCompany = 1;
    public static final int BuyForOther = 2;
    
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * potential_customer.id
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * potential_customer.member_id
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private Long memberId;

    private String connectMobile;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * potential_customer.car_model
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private String carModel;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * potential_customer.car_type
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private String carType;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * potential_customer.car_color
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private String carColor;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * potential_customer.buy_time
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private Long buyTime;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * potential_customer.buy_for
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private String buyFor;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * potential_customer.buy_budget
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private String buyBudget;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * potential_customer.buy_date
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private Long buyDate;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * potential_customer.pay_type
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private Integer payType;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * potential_customer.create_at
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private Long createAt;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * potential_customer.create_by
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private Long createBy;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * potential_customer.update_at
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private Long updateAt;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * potential_customer.update_by
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private Long updateBy;

    private Long serviceBy;
    private String serviceByName;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getMemberId() {
        return memberId;
    }

    public void setMemberId(Long memberId) {
        this.memberId = memberId;
    }

    public String getConnectMobile() {
        return connectMobile;
    }

    public void setConnectMobile(String connectMobile) {
        this.connectMobile = connectMobile;
    }

    public String getCarModel() {
        return carModel;
    }

    public void setCarModel(String carModel) {
        this.carModel = carModel;
    }

    public String getCarType() {
        return carType;
    }

    public void setCarType(String carType) {
        this.carType = carType;
    }

    public String getCarColor() {
        return carColor;
    }

    public void setCarColor(String carColor) {
        this.carColor = carColor;
    }

    public Long getBuyTime() {
        return buyTime;
    }

    public void setBuyTime(Long buyTime) {
        this.buyTime = buyTime;
    }

    public String getBuyFor() {
        return buyFor;
    }

    public void setBuyFor(String buyFor) {
        this.buyFor = buyFor;
    }

    public String getBuyBudget() {
        return buyBudget;
    }

    public void setBuyBudget(String buyBudget) {
        this.buyBudget = buyBudget;
    }

    public Long getBuyDate() {
        return buyDate;
    }

    public void setBuyDate(Long buyDate) {
        this.buyDate = buyDate;
    }

    public Integer getPayType() {
        return payType;
    }

    public void setPayType(Integer payType) {
        this.payType = payType;
    }

    public Long getCreateAt() {
        return createAt;
    }

    public void setCreateAt(Long createAt) {
        this.createAt = createAt;
    }

    public Long getCreateBy() {
        return createBy;
    }

    public void setCreateBy(Long createBy) {
        this.createBy = createBy;
    }

    public Long getUpdateAt() {
        return updateAt;
    }

    public void setUpdateAt(Long updateAt) {
        this.updateAt = updateAt;
    }

    public Long getUpdateBy() {
        return updateBy;
    }

    public void setUpdateBy(Long updateBy) {
        this.updateBy = updateBy;
    }

    public Long getServiceBy() {
        return serviceBy;
    }

    public void setServiceBy(Long serviceBy) {
        this.serviceBy = serviceBy;
    }

    public String getServiceByName() {
        return serviceByName;
    }

    public void setServiceByName(String serviceByName) {
        this.serviceByName = serviceByName;
    }

}