package com.yongjia.model;

public class Saler {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column saler.id
	 * @mbggenerated  Sun Jun 14 20:57:12 CST 2015
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column saler.name
	 * @mbggenerated  Sun Jun 14 20:57:12 CST 2015
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column saler.mobile
	 * @mbggenerated  Sun Jun 14 20:57:12 CST 2015
	 */
	private String mobile;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column saler.work_no
	 * @mbggenerated  Sun Jun 14 20:57:12 CST 2015
	 */
	private String workNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column saler.account
	 * @mbggenerated  Sun Jun 14 20:57:12 CST 2015
	 */
	private String account;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column saler.pwd
	 * @mbggenerated  Sun Jun 14 20:57:12 CST 2015
	 */
	private String pwd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column saler.status
	 * @mbggenerated  Sun Jun 14 20:57:12 CST 2015
	 */
	private Byte status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column saler.create_by
	 * @mbggenerated  Sun Jun 14 20:57:12 CST 2015
	 */
	private Integer createBy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column saler.create_at
	 * @mbggenerated  Sun Jun 14 20:57:12 CST 2015
	 */
	private Integer createAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column saler.update_by
	 * @mbggenerated  Sun Jun 14 20:57:12 CST 2015
	 */
	private Integer updateBy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column saler.update_at
	 * @mbggenerated  Sun Jun 14 20:57:12 CST 2015
	 */
	private Integer updateAt;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column saler.id
	 * @return  the value of saler.id
	 * @mbggenerated  Sun Jun 14 20:57:12 CST 2015
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column saler.id
	 * @param id  the value for saler.id
	 * @mbggenerated  Sun Jun 14 20:57:12 CST 2015
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column saler.name
	 * @return  the value of saler.name
	 * @mbggenerated  Sun Jun 14 20:57:12 CST 2015
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column saler.name
	 * @param name  the value for saler.name
	 * @mbggenerated  Sun Jun 14 20:57:12 CST 2015
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column saler.mobile
	 * @return  the value of saler.mobile
	 * @mbggenerated  Sun Jun 14 20:57:12 CST 2015
	 */
	public String getMobile() {
		return mobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column saler.mobile
	 * @param mobile  the value for saler.mobile
	 * @mbggenerated  Sun Jun 14 20:57:12 CST 2015
	 */
	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column saler.work_no
	 * @return  the value of saler.work_no
	 * @mbggenerated  Sun Jun 14 20:57:12 CST 2015
	 */
	public String getWorkNo() {
		return workNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column saler.work_no
	 * @param workNo  the value for saler.work_no
	 * @mbggenerated  Sun Jun 14 20:57:12 CST 2015
	 */
	public void setWorkNo(String workNo) {
		this.workNo = workNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column saler.account
	 * @return  the value of saler.account
	 * @mbggenerated  Sun Jun 14 20:57:12 CST 2015
	 */
	public String getAccount() {
		return account;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column saler.account
	 * @param account  the value for saler.account
	 * @mbggenerated  Sun Jun 14 20:57:12 CST 2015
	 */
	public void setAccount(String account) {
		this.account = account;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column saler.pwd
	 * @return  the value of saler.pwd
	 * @mbggenerated  Sun Jun 14 20:57:12 CST 2015
	 */
	public String getPwd() {
		return pwd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column saler.pwd
	 * @param pwd  the value for saler.pwd
	 * @mbggenerated  Sun Jun 14 20:57:12 CST 2015
	 */
	public void setPwd(String pwd) {
		this.pwd = pwd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column saler.status
	 * @return  the value of saler.status
	 * @mbggenerated  Sun Jun 14 20:57:12 CST 2015
	 */
	public Byte getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column saler.status
	 * @param status  the value for saler.status
	 * @mbggenerated  Sun Jun 14 20:57:12 CST 2015
	 */
	public void setStatus(Byte status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column saler.create_by
	 * @return  the value of saler.create_by
	 * @mbggenerated  Sun Jun 14 20:57:12 CST 2015
	 */
	public Integer getCreateBy() {
		return createBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column saler.create_by
	 * @param createBy  the value for saler.create_by
	 * @mbggenerated  Sun Jun 14 20:57:12 CST 2015
	 */
	public void setCreateBy(Integer createBy) {
		this.createBy = createBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column saler.create_at
	 * @return  the value of saler.create_at
	 * @mbggenerated  Sun Jun 14 20:57:12 CST 2015
	 */
	public Integer getCreateAt() {
		return createAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column saler.create_at
	 * @param createAt  the value for saler.create_at
	 * @mbggenerated  Sun Jun 14 20:57:12 CST 2015
	 */
	public void setCreateAt(Integer createAt) {
		this.createAt = createAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column saler.update_by
	 * @return  the value of saler.update_by
	 * @mbggenerated  Sun Jun 14 20:57:12 CST 2015
	 */
	public Integer getUpdateBy() {
		return updateBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column saler.update_by
	 * @param updateBy  the value for saler.update_by
	 * @mbggenerated  Sun Jun 14 20:57:12 CST 2015
	 */
	public void setUpdateBy(Integer updateBy) {
		this.updateBy = updateBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column saler.update_at
	 * @return  the value of saler.update_at
	 * @mbggenerated  Sun Jun 14 20:57:12 CST 2015
	 */
	public Integer getUpdateAt() {
		return updateAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column saler.update_at
	 * @param updateAt  the value for saler.update_at
	 * @mbggenerated  Sun Jun 14 20:57:12 CST 2015
	 */
	public void setUpdateAt(Integer updateAt) {
		this.updateAt = updateAt;
	}
}