package com.yongjia.model;

public class SignPointConfig {
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column sign_point_config.id
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * sign_point_config.day
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private String month;

    private Integer times;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * sign_point_config.point
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private Integer point;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * sign_point_config.create_at
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private Integer createAt;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * sign_point_config.create_by
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private Integer createBy;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * sign_point_config.update_at
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private Integer updateAt;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * sign_point_config.update_by
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private Integer updateBy;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * sign_point_config.id
     * 
     * @return the value of sign_point_config.id
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * sign_point_config.id
     * 
     * @param id the value for sign_point_config.id
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    public String getMonth() {
        return month;
    }

    public void setMonth(String month) {
        this.month = month;
    }

    public Integer getTimes() {
        return times;
    }

    public void setTimes(Integer times) {
        this.times = times;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * sign_point_config.point
     * 
     * @return the value of sign_point_config.point
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public Integer getPoint() {
        return point;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * sign_point_config.point
     * 
     * @param point the value for sign_point_config.point
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setPoint(Integer point) {
        this.point = point;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * sign_point_config.create_at
     * 
     * @return the value of sign_point_config.create_at
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public Integer getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * sign_point_config.create_at
     * 
     * @param createAt the value for sign_point_config.create_at
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setCreateAt(Integer createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * sign_point_config.create_by
     * 
     * @return the value of sign_point_config.create_by
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public Integer getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * sign_point_config.create_by
     * 
     * @param createBy the value for sign_point_config.create_by
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setCreateBy(Integer createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * sign_point_config.update_at
     * 
     * @return the value of sign_point_config.update_at
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public Integer getUpdateAt() {
        return updateAt;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * sign_point_config.update_at
     * 
     * @param updateAt the value for sign_point_config.update_at
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setUpdateAt(Integer updateAt) {
        this.updateAt = updateAt;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * sign_point_config.update_by
     * 
     * @return the value of sign_point_config.update_by
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public Integer getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * sign_point_config.update_by
     * 
     * @param updateBy the value for sign_point_config.update_by
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setUpdateBy(Integer updateBy) {
        this.updateBy = updateBy;
    }
}