package com.yongjia.model;

public class SmsSendRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_send_record.id
     *
     * @mbggenerated Thu Jul 30 15:41:09 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_send_record.mobile
     *
     * @mbggenerated Thu Jul 30 15:41:09 CST 2015
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_send_record.code
     *
     * @mbggenerated Thu Jul 30 15:41:09 CST 2015
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_send_record.tpl
     *
     * @mbggenerated Thu Jul 30 15:41:09 CST 2015
     */
    private String tpl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_send_record.create_at
     *
     * @mbggenerated Thu Jul 30 15:41:09 CST 2015
     */
    private Long createAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_send_record.id
     *
     * @return the value of sms_send_record.id
     *
     * @mbggenerated Thu Jul 30 15:41:09 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_send_record.id
     *
     * @param id the value for sms_send_record.id
     *
     * @mbggenerated Thu Jul 30 15:41:09 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_send_record.mobile
     *
     * @return the value of sms_send_record.mobile
     *
     * @mbggenerated Thu Jul 30 15:41:09 CST 2015
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_send_record.mobile
     *
     * @param mobile the value for sms_send_record.mobile
     *
     * @mbggenerated Thu Jul 30 15:41:09 CST 2015
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_send_record.code
     *
     * @return the value of sms_send_record.code
     *
     * @mbggenerated Thu Jul 30 15:41:09 CST 2015
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_send_record.code
     *
     * @param code the value for sms_send_record.code
     *
     * @mbggenerated Thu Jul 30 15:41:09 CST 2015
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_send_record.tpl
     *
     * @return the value of sms_send_record.tpl
     *
     * @mbggenerated Thu Jul 30 15:41:09 CST 2015
     */
    public String getTpl() {
        return tpl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_send_record.tpl
     *
     * @param tpl the value for sms_send_record.tpl
     *
     * @mbggenerated Thu Jul 30 15:41:09 CST 2015
     */
    public void setTpl(String tpl) {
        this.tpl = tpl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_send_record.create_at
     *
     * @return the value of sms_send_record.create_at
     *
     * @mbggenerated Thu Jul 30 15:41:09 CST 2015
     */
    public Long getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_send_record.create_at
     *
     * @param createAt the value for sms_send_record.create_at
     *
     * @mbggenerated Thu Jul 30 15:41:09 CST 2015
     */
    public void setCreateAt(Long createAt) {
        this.createAt = createAt;
    }
}