package com.yongjia.model;

public class User {

    public static final int StatusStop = 1;
    public static final int StatusActive = 0;

    public static final int RoleAdmin = 1;
    public static final int RoleManager = 2;
    public static final int RoleService = 3;
    public static final int RoleSaler = 4;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column user.id
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private Long id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column user.name
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private String name;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column user.mobile
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private String mobile;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column user.work_no
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private String workNo;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column user.account
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private String account;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column user.pwd
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private String pwd;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column user.role_id
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private Integer roleId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column user.status
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private Integer status;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column user.create_by
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private Long createBy;
    private String openid;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column user.create_at
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private Long createAt;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column user.update_by
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private Long updateBy;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column user.update_at
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private Long updateAt;

    public String getOpenid() {
        return openid;
    }

    public void setOpenid(String openid) {
        this.openid = openid;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getCreateBy() {
        return createBy;
    }

    public void setCreateBy(Long createBy) {
        this.createBy = createBy;
    }

    public Long getCreateAt() {
        return createAt;
    }

    public void setCreateAt(Long createAt) {
        this.createAt = createAt;
    }

    public Long getUpdateBy() {
        return updateBy;
    }

    public void setUpdateBy(Long updateBy) {
        this.updateBy = updateBy;
    }

    public Long getUpdateAt() {
        return updateAt;
    }

    public void setUpdateAt(Long updateAt) {
        this.updateAt = updateAt;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column user.name
     * 
     * @return the value of user.name
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column user.name
     * 
     * @param name the value for user.name
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column user.mobile
     * 
     * @return the value of user.mobile
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column user.mobile
     * 
     * @param mobile the value for user.mobile
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column user.work_no
     * 
     * @return the value of user.work_no
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public String getWorkNo() {
        return workNo;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column user.work_no
     * 
     * @param workNo the value for user.work_no
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setWorkNo(String workNo) {
        this.workNo = workNo;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column user.account
     * 
     * @return the value of user.account
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column user.account
     * 
     * @param account the value for user.account
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setAccount(String account) {
        this.account = account;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column user.pwd
     * 
     * @return the value of user.pwd
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public String getPwd() {
        return pwd;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column user.pwd
     * 
     * @param pwd the value for user.pwd
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setPwd(String pwd) {
        this.pwd = pwd;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column user.role_id
     * 
     * @return the value of user.role_id
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column user.role_id
     * 
     * @param roleId the value for user.role_id
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column user.status
     * 
     * @return the value of user.status
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column user.status
     * 
     * @param status the value for user.status
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

}