package com.yongjia.model;

public class WxMessage {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_message.id
	 * @mbggenerated  Tue Jul 07 14:25:04 CST 2015
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_message.msg_name
	 * @mbggenerated  Tue Jul 07 14:25:04 CST 2015
	 */
	private String msgName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_message.type
	 * @mbggenerated  Tue Jul 07 14:25:04 CST 2015
	 */
	private Integer type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_message.msg_type
	 * @mbggenerated  Tue Jul 07 14:25:04 CST 2015
	 */
	private Integer msgType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_message.status
	 * @mbggenerated  Tue Jul 07 14:25:04 CST 2015
	 */
	private Integer status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_message.update_at
	 * @mbggenerated  Tue Jul 07 14:25:04 CST 2015
	 */
	private Long updateAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_message.update_by
	 * @mbggenerated  Tue Jul 07 14:25:04 CST 2015
	 */
	private Long updateBy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_message.create_at
	 * @mbggenerated  Tue Jul 07 14:25:04 CST 2015
	 */
	private Long createAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_message.create_by
	 * @mbggenerated  Tue Jul 07 14:25:04 CST 2015
	 */
	private Long createBy;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_message.id
	 * @return  the value of wx_message.id
	 * @mbggenerated  Tue Jul 07 14:25:04 CST 2015
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_message.id
	 * @param id  the value for wx_message.id
	 * @mbggenerated  Tue Jul 07 14:25:04 CST 2015
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_message.msg_name
	 * @return  the value of wx_message.msg_name
	 * @mbggenerated  Tue Jul 07 14:25:04 CST 2015
	 */
	public String getMsgName() {
		return msgName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_message.msg_name
	 * @param msgName  the value for wx_message.msg_name
	 * @mbggenerated  Tue Jul 07 14:25:04 CST 2015
	 */
	public void setMsgName(String msgName) {
		this.msgName = msgName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_message.type
	 * @return  the value of wx_message.type
	 * @mbggenerated  Tue Jul 07 14:25:04 CST 2015
	 */
	public Integer getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_message.type
	 * @param type  the value for wx_message.type
	 * @mbggenerated  Tue Jul 07 14:25:04 CST 2015
	 */
	public void setType(Integer type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_message.msg_type
	 * @return  the value of wx_message.msg_type
	 * @mbggenerated  Tue Jul 07 14:25:04 CST 2015
	 */
	public Integer getMsgType() {
		return msgType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_message.msg_type
	 * @param msgType  the value for wx_message.msg_type
	 * @mbggenerated  Tue Jul 07 14:25:04 CST 2015
	 */
	public void setMsgType(Integer msgType) {
		this.msgType = msgType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_message.status
	 * @return  the value of wx_message.status
	 * @mbggenerated  Tue Jul 07 14:25:04 CST 2015
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_message.status
	 * @param status  the value for wx_message.status
	 * @mbggenerated  Tue Jul 07 14:25:04 CST 2015
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_message.update_at
	 * @return  the value of wx_message.update_at
	 * @mbggenerated  Tue Jul 07 14:25:04 CST 2015
	 */
	public Long getUpdateAt() {
		return updateAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_message.update_at
	 * @param updateAt  the value for wx_message.update_at
	 * @mbggenerated  Tue Jul 07 14:25:04 CST 2015
	 */
	public void setUpdateAt(Long updateAt) {
		this.updateAt = updateAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_message.update_by
	 * @return  the value of wx_message.update_by
	 * @mbggenerated  Tue Jul 07 14:25:04 CST 2015
	 */
	public Long getUpdateBy() {
		return updateBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_message.update_by
	 * @param updateBy  the value for wx_message.update_by
	 * @mbggenerated  Tue Jul 07 14:25:04 CST 2015
	 */
	public void setUpdateBy(Long updateBy) {
		this.updateBy = updateBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_message.create_at
	 * @return  the value of wx_message.create_at
	 * @mbggenerated  Tue Jul 07 14:25:04 CST 2015
	 */
	public Long getCreateAt() {
		return createAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_message.create_at
	 * @param createAt  the value for wx_message.create_at
	 * @mbggenerated  Tue Jul 07 14:25:04 CST 2015
	 */
	public void setCreateAt(Long createAt) {
		this.createAt = createAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_message.create_by
	 * @return  the value of wx_message.create_by
	 * @mbggenerated  Tue Jul 07 14:25:04 CST 2015
	 */
	public Long getCreateBy() {
		return createBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_message.create_by
	 * @param createBy  the value for wx_message.create_by
	 * @mbggenerated  Tue Jul 07 14:25:04 CST 2015
	 */
	public void setCreateBy(Long createBy) {
		this.createBy = createBy;
	}
}