package com.yongjia.model;

public class WxMsgItem {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column wx_msg_item.id
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private Integer id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column wx_msg_item.msg_id
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private Integer wxMsgId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column wx_msg_item.title
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private Integer messageId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * wx_msg_item.descipition
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private String url;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column wx_msg_item.sort
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private Integer sort;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * wx_msg_item.create_at
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private Integer createAt;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * wx_msg_item.create_by
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private Integer createBy;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * wx_msg_item.modify_at
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private Integer modifyAt;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * wx_msg_item.modify_by
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private Integer modifyBy;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column wx_msg_item.content
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */

    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column wx_msg_item.id
     * 
     * @param id the value for wx_msg_item.id
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * wx_msg_item.url
     * 
     * @return the value of wx_msg_item.url
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column wx_msg_item.url
     * 
     * @param url the value for wx_msg_item.url
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * wx_msg_item.sort
     * 
     * @return the value of wx_msg_item.sort
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * wx_msg_item.sort
     * 
     * @param sort the value for wx_msg_item.sort
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * wx_msg_item.create_at
     * 
     * @return the value of wx_msg_item.create_at
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public Integer getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * wx_msg_item.create_at
     * 
     * @param createAt the value for wx_msg_item.create_at
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setCreateAt(Integer createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * wx_msg_item.create_by
     * 
     * @return the value of wx_msg_item.create_by
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public Integer getCreateBy() {
        return createBy;
    }

    public Integer getWxMsgId() {
        return wxMsgId;
    }

    public void setWxMsgId(Integer wxMsgId) {
        this.wxMsgId = wxMsgId;
    }

    public Integer getMessageId() {
        return messageId;
    }

    public void setMessageId(Integer messageId) {
        this.messageId = messageId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * wx_msg_item.create_by
     * 
     * @param createBy the value for wx_msg_item.create_by
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setCreateBy(Integer createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * wx_msg_item.modify_at
     * 
     * @return the value of wx_msg_item.modify_at
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public Integer getModifyAt() {
        return modifyAt;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * wx_msg_item.modify_at
     * 
     * @param modifyAt the value for wx_msg_item.modify_at
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setModifyAt(Integer modifyAt) {
        this.modifyAt = modifyAt;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * wx_msg_item.modify_by
     * 
     * @return the value of wx_msg_item.modify_by
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public Integer getModifyBy() {
        return modifyBy;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * wx_msg_item.modify_by
     * 
     * @param modifyBy the value for wx_msg_item.modify_by
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setModifyBy(Integer modifyBy) {
        this.modifyBy = modifyBy;
    }

}