package com.yongjia.model;

public class WxMsgItem {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_msg_item.id
	 * @mbggenerated  Sun Jun 14 20:37:53 CST 2015
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_msg_item.msg_id
	 * @mbggenerated  Sun Jun 14 20:37:53 CST 2015
	 */
	private Integer msgId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_msg_item.title
	 * @mbggenerated  Sun Jun 14 20:37:53 CST 2015
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_msg_item.desc
	 * @mbggenerated  Sun Jun 14 20:37:53 CST 2015
	 */
	private String desc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_msg_item.author
	 * @mbggenerated  Sun Jun 14 20:37:53 CST 2015
	 */
	private String author;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_msg_item.pic
	 * @mbggenerated  Sun Jun 14 20:37:53 CST 2015
	 */
	private String pic;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_msg_item.url
	 * @mbggenerated  Sun Jun 14 20:37:53 CST 2015
	 */
	private String url;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_msg_item.sort
	 * @mbggenerated  Sun Jun 14 20:37:53 CST 2015
	 */
	private Integer sort;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_msg_item.create_at
	 * @mbggenerated  Sun Jun 14 20:37:53 CST 2015
	 */
	private Integer createAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_msg_item.create_by
	 * @mbggenerated  Sun Jun 14 20:37:53 CST 2015
	 */
	private Integer createBy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_msg_item.modify_at
	 * @mbggenerated  Sun Jun 14 20:37:53 CST 2015
	 */
	private Integer modifyAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_msg_item.modify_by
	 * @mbggenerated  Sun Jun 14 20:37:53 CST 2015
	 */
	private Integer modifyBy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_msg_item.content
	 * @mbggenerated  Sun Jun 14 20:37:53 CST 2015
	 */
	private String content;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_msg_item.id
	 * @return  the value of wx_msg_item.id
	 * @mbggenerated  Sun Jun 14 20:37:53 CST 2015
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_msg_item.id
	 * @param id  the value for wx_msg_item.id
	 * @mbggenerated  Sun Jun 14 20:37:53 CST 2015
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_msg_item.msg_id
	 * @return  the value of wx_msg_item.msg_id
	 * @mbggenerated  Sun Jun 14 20:37:53 CST 2015
	 */
	public Integer getMsgId() {
		return msgId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_msg_item.msg_id
	 * @param msgId  the value for wx_msg_item.msg_id
	 * @mbggenerated  Sun Jun 14 20:37:53 CST 2015
	 */
	public void setMsgId(Integer msgId) {
		this.msgId = msgId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_msg_item.title
	 * @return  the value of wx_msg_item.title
	 * @mbggenerated  Sun Jun 14 20:37:53 CST 2015
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_msg_item.title
	 * @param title  the value for wx_msg_item.title
	 * @mbggenerated  Sun Jun 14 20:37:53 CST 2015
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_msg_item.desc
	 * @return  the value of wx_msg_item.desc
	 * @mbggenerated  Sun Jun 14 20:37:53 CST 2015
	 */
	public String getDesc() {
		return desc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_msg_item.desc
	 * @param desc  the value for wx_msg_item.desc
	 * @mbggenerated  Sun Jun 14 20:37:53 CST 2015
	 */
	public void setDesc(String desc) {
		this.desc = desc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_msg_item.author
	 * @return  the value of wx_msg_item.author
	 * @mbggenerated  Sun Jun 14 20:37:53 CST 2015
	 */
	public String getAuthor() {
		return author;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_msg_item.author
	 * @param author  the value for wx_msg_item.author
	 * @mbggenerated  Sun Jun 14 20:37:53 CST 2015
	 */
	public void setAuthor(String author) {
		this.author = author;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_msg_item.pic
	 * @return  the value of wx_msg_item.pic
	 * @mbggenerated  Sun Jun 14 20:37:53 CST 2015
	 */
	public String getPic() {
		return pic;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_msg_item.pic
	 * @param pic  the value for wx_msg_item.pic
	 * @mbggenerated  Sun Jun 14 20:37:53 CST 2015
	 */
	public void setPic(String pic) {
		this.pic = pic;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_msg_item.url
	 * @return  the value of wx_msg_item.url
	 * @mbggenerated  Sun Jun 14 20:37:53 CST 2015
	 */
	public String getUrl() {
		return url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_msg_item.url
	 * @param url  the value for wx_msg_item.url
	 * @mbggenerated  Sun Jun 14 20:37:53 CST 2015
	 */
	public void setUrl(String url) {
		this.url = url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_msg_item.sort
	 * @return  the value of wx_msg_item.sort
	 * @mbggenerated  Sun Jun 14 20:37:53 CST 2015
	 */
	public Integer getSort() {
		return sort;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_msg_item.sort
	 * @param sort  the value for wx_msg_item.sort
	 * @mbggenerated  Sun Jun 14 20:37:53 CST 2015
	 */
	public void setSort(Integer sort) {
		this.sort = sort;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_msg_item.create_at
	 * @return  the value of wx_msg_item.create_at
	 * @mbggenerated  Sun Jun 14 20:37:53 CST 2015
	 */
	public Integer getCreateAt() {
		return createAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_msg_item.create_at
	 * @param createAt  the value for wx_msg_item.create_at
	 * @mbggenerated  Sun Jun 14 20:37:53 CST 2015
	 */
	public void setCreateAt(Integer createAt) {
		this.createAt = createAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_msg_item.create_by
	 * @return  the value of wx_msg_item.create_by
	 * @mbggenerated  Sun Jun 14 20:37:53 CST 2015
	 */
	public Integer getCreateBy() {
		return createBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_msg_item.create_by
	 * @param createBy  the value for wx_msg_item.create_by
	 * @mbggenerated  Sun Jun 14 20:37:53 CST 2015
	 */
	public void setCreateBy(Integer createBy) {
		this.createBy = createBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_msg_item.modify_at
	 * @return  the value of wx_msg_item.modify_at
	 * @mbggenerated  Sun Jun 14 20:37:53 CST 2015
	 */
	public Integer getModifyAt() {
		return modifyAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_msg_item.modify_at
	 * @param modifyAt  the value for wx_msg_item.modify_at
	 * @mbggenerated  Sun Jun 14 20:37:53 CST 2015
	 */
	public void setModifyAt(Integer modifyAt) {
		this.modifyAt = modifyAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_msg_item.modify_by
	 * @return  the value of wx_msg_item.modify_by
	 * @mbggenerated  Sun Jun 14 20:37:53 CST 2015
	 */
	public Integer getModifyBy() {
		return modifyBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_msg_item.modify_by
	 * @param modifyBy  the value for wx_msg_item.modify_by
	 * @mbggenerated  Sun Jun 14 20:37:53 CST 2015
	 */
	public void setModifyBy(Integer modifyBy) {
		this.modifyBy = modifyBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_msg_item.content
	 * @return  the value of wx_msg_item.content
	 * @mbggenerated  Sun Jun 14 20:37:53 CST 2015
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_msg_item.content
	 * @param content  the value for wx_msg_item.content
	 * @mbggenerated  Sun Jun 14 20:37:53 CST 2015
	 */
	public void setContent(String content) {
		this.content = content;
	}
}