package com.yongjia.model;

public class WxRuleKeyword {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_rule_keyword.id
	 * @mbggenerated  Tue Jul 07 14:25:04 CST 2015
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_rule_keyword.rule_id
	 * @mbggenerated  Tue Jul 07 14:25:04 CST 2015
	 */
	private Integer ruleId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_rule_keyword.keyword
	 * @mbggenerated  Tue Jul 07 14:25:04 CST 2015
	 */
	private String keyword;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_rule_keyword.create_by
	 * @mbggenerated  Tue Jul 07 14:25:04 CST 2015
	 */
	private Integer createBy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_rule_keyword.create_at
	 * @mbggenerated  Tue Jul 07 14:25:04 CST 2015
	 */
	private Integer createAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_rule_keyword.update_by
	 * @mbggenerated  Tue Jul 07 14:25:04 CST 2015
	 */
	private Integer updateBy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_rule_keyword.update_at
	 * @mbggenerated  Tue Jul 07 14:25:04 CST 2015
	 */
	private Integer updateAt;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_rule_keyword.id
	 * @return  the value of wx_rule_keyword.id
	 * @mbggenerated  Tue Jul 07 14:25:04 CST 2015
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_rule_keyword.id
	 * @param id  the value for wx_rule_keyword.id
	 * @mbggenerated  Tue Jul 07 14:25:04 CST 2015
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_rule_keyword.rule_id
	 * @return  the value of wx_rule_keyword.rule_id
	 * @mbggenerated  Tue Jul 07 14:25:04 CST 2015
	 */
	public Integer getRuleId() {
		return ruleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_rule_keyword.rule_id
	 * @param ruleId  the value for wx_rule_keyword.rule_id
	 * @mbggenerated  Tue Jul 07 14:25:04 CST 2015
	 */
	public void setRuleId(Integer ruleId) {
		this.ruleId = ruleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_rule_keyword.keyword
	 * @return  the value of wx_rule_keyword.keyword
	 * @mbggenerated  Tue Jul 07 14:25:04 CST 2015
	 */
	public String getKeyword() {
		return keyword;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_rule_keyword.keyword
	 * @param keyword  the value for wx_rule_keyword.keyword
	 * @mbggenerated  Tue Jul 07 14:25:04 CST 2015
	 */
	public void setKeyword(String keyword) {
		this.keyword = keyword;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_rule_keyword.create_by
	 * @return  the value of wx_rule_keyword.create_by
	 * @mbggenerated  Tue Jul 07 14:25:04 CST 2015
	 */
	public Integer getCreateBy() {
		return createBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_rule_keyword.create_by
	 * @param createBy  the value for wx_rule_keyword.create_by
	 * @mbggenerated  Tue Jul 07 14:25:04 CST 2015
	 */
	public void setCreateBy(Integer createBy) {
		this.createBy = createBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_rule_keyword.create_at
	 * @return  the value of wx_rule_keyword.create_at
	 * @mbggenerated  Tue Jul 07 14:25:04 CST 2015
	 */
	public Integer getCreateAt() {
		return createAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_rule_keyword.create_at
	 * @param createAt  the value for wx_rule_keyword.create_at
	 * @mbggenerated  Tue Jul 07 14:25:04 CST 2015
	 */
	public void setCreateAt(Integer createAt) {
		this.createAt = createAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_rule_keyword.update_by
	 * @return  the value of wx_rule_keyword.update_by
	 * @mbggenerated  Tue Jul 07 14:25:04 CST 2015
	 */
	public Integer getUpdateBy() {
		return updateBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_rule_keyword.update_by
	 * @param updateBy  the value for wx_rule_keyword.update_by
	 * @mbggenerated  Tue Jul 07 14:25:04 CST 2015
	 */
	public void setUpdateBy(Integer updateBy) {
		this.updateBy = updateBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_rule_keyword.update_at
	 * @return  the value of wx_rule_keyword.update_at
	 * @mbggenerated  Tue Jul 07 14:25:04 CST 2015
	 */
	public Integer getUpdateAt() {
		return updateAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_rule_keyword.update_at
	 * @param updateAt  the value for wx_rule_keyword.update_at
	 * @mbggenerated  Tue Jul 07 14:25:04 CST 2015
	 */
	public void setUpdateAt(Integer updateAt) {
		this.updateAt = updateAt;
	}
}