package com.yongjia.model;

public class WxRule {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_rule.id
	 * @mbggenerated  Fri Jun 12 16:17:02 CST 2015
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_rule.name
	 * @mbggenerated  Fri Jun 12 16:17:02 CST 2015
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_rule.msg_id
	 * @mbggenerated  Fri Jun 12 16:17:02 CST 2015
	 */
	private Integer msgId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_rule.create_by
	 * @mbggenerated  Fri Jun 12 16:17:02 CST 2015
	 */
	private Integer createBy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_rule.create_at
	 * @mbggenerated  Fri Jun 12 16:17:02 CST 2015
	 */
	private Integer createAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_rule.update_by
	 * @mbggenerated  Fri Jun 12 16:17:02 CST 2015
	 */
	private Integer updateBy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_rule.update_at
	 * @mbggenerated  Fri Jun 12 16:17:02 CST 2015
	 */
	private Integer updateAt;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_rule.id
	 * @return  the value of wx_rule.id
	 * @mbggenerated  Fri Jun 12 16:17:02 CST 2015
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_rule.id
	 * @param id  the value for wx_rule.id
	 * @mbggenerated  Fri Jun 12 16:17:02 CST 2015
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_rule.name
	 * @return  the value of wx_rule.name
	 * @mbggenerated  Fri Jun 12 16:17:02 CST 2015
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_rule.name
	 * @param name  the value for wx_rule.name
	 * @mbggenerated  Fri Jun 12 16:17:02 CST 2015
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_rule.msg_id
	 * @return  the value of wx_rule.msg_id
	 * @mbggenerated  Fri Jun 12 16:17:02 CST 2015
	 */
	public Integer getMsgId() {
		return msgId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_rule.msg_id
	 * @param msgId  the value for wx_rule.msg_id
	 * @mbggenerated  Fri Jun 12 16:17:02 CST 2015
	 */
	public void setMsgId(Integer msgId) {
		this.msgId = msgId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_rule.create_by
	 * @return  the value of wx_rule.create_by
	 * @mbggenerated  Fri Jun 12 16:17:02 CST 2015
	 */
	public Integer getCreateBy() {
		return createBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_rule.create_by
	 * @param createBy  the value for wx_rule.create_by
	 * @mbggenerated  Fri Jun 12 16:17:02 CST 2015
	 */
	public void setCreateBy(Integer createBy) {
		this.createBy = createBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_rule.create_at
	 * @return  the value of wx_rule.create_at
	 * @mbggenerated  Fri Jun 12 16:17:02 CST 2015
	 */
	public Integer getCreateAt() {
		return createAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_rule.create_at
	 * @param createAt  the value for wx_rule.create_at
	 * @mbggenerated  Fri Jun 12 16:17:02 CST 2015
	 */
	public void setCreateAt(Integer createAt) {
		this.createAt = createAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_rule.update_by
	 * @return  the value of wx_rule.update_by
	 * @mbggenerated  Fri Jun 12 16:17:02 CST 2015
	 */
	public Integer getUpdateBy() {
		return updateBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_rule.update_by
	 * @param updateBy  the value for wx_rule.update_by
	 * @mbggenerated  Fri Jun 12 16:17:02 CST 2015
	 */
	public void setUpdateBy(Integer updateBy) {
		this.updateBy = updateBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_rule.update_at
	 * @return  the value of wx_rule.update_at
	 * @mbggenerated  Fri Jun 12 16:17:02 CST 2015
	 */
	public Integer getUpdateAt() {
		return updateAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_rule.update_at
	 * @param updateAt  the value for wx_rule.update_at
	 * @mbggenerated  Fri Jun 12 16:17:02 CST 2015
	 */
	public void setUpdateAt(Integer updateAt) {
		this.updateAt = updateAt;
	}
}