package com.yongjia.model;

public class WxRuleKeyword {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_rule_keyword.id
	 * @mbggenerated  Sun Jun 14 20:37:53 CST 2015
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_rule_keyword.rule_id
	 * @mbggenerated  Sun Jun 14 20:37:53 CST 2015
	 */
	private Integer ruleId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_rule_keyword.key
	 * @mbggenerated  Sun Jun 14 20:37:53 CST 2015
	 */
	private String key;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_rule_keyword.create_by
	 * @mbggenerated  Sun Jun 14 20:37:53 CST 2015
	 */
	private Integer createBy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_rule_keyword.create_at
	 * @mbggenerated  Sun Jun 14 20:37:53 CST 2015
	 */
	private Integer createAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_rule_keyword.update_by
	 * @mbggenerated  Sun Jun 14 20:37:53 CST 2015
	 */
	private Integer updateBy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_rule_keyword.update_at
	 * @mbggenerated  Sun Jun 14 20:37:53 CST 2015
	 */
	private Integer updateAt;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_rule_keyword.id
	 * @return  the value of wx_rule_keyword.id
	 * @mbggenerated  Sun Jun 14 20:37:53 CST 2015
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_rule_keyword.id
	 * @param id  the value for wx_rule_keyword.id
	 * @mbggenerated  Sun Jun 14 20:37:53 CST 2015
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_rule_keyword.rule_id
	 * @return  the value of wx_rule_keyword.rule_id
	 * @mbggenerated  Sun Jun 14 20:37:53 CST 2015
	 */
	public Integer getRuleId() {
		return ruleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_rule_keyword.rule_id
	 * @param ruleId  the value for wx_rule_keyword.rule_id
	 * @mbggenerated  Sun Jun 14 20:37:53 CST 2015
	 */
	public void setRuleId(Integer ruleId) {
		this.ruleId = ruleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_rule_keyword.key
	 * @return  the value of wx_rule_keyword.key
	 * @mbggenerated  Sun Jun 14 20:37:53 CST 2015
	 */
	public String getKey() {
		return key;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_rule_keyword.key
	 * @param key  the value for wx_rule_keyword.key
	 * @mbggenerated  Sun Jun 14 20:37:53 CST 2015
	 */
	public void setKey(String key) {
		this.key = key;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_rule_keyword.create_by
	 * @return  the value of wx_rule_keyword.create_by
	 * @mbggenerated  Sun Jun 14 20:37:53 CST 2015
	 */
	public Integer getCreateBy() {
		return createBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_rule_keyword.create_by
	 * @param createBy  the value for wx_rule_keyword.create_by
	 * @mbggenerated  Sun Jun 14 20:37:53 CST 2015
	 */
	public void setCreateBy(Integer createBy) {
		this.createBy = createBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_rule_keyword.create_at
	 * @return  the value of wx_rule_keyword.create_at
	 * @mbggenerated  Sun Jun 14 20:37:53 CST 2015
	 */
	public Integer getCreateAt() {
		return createAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_rule_keyword.create_at
	 * @param createAt  the value for wx_rule_keyword.create_at
	 * @mbggenerated  Sun Jun 14 20:37:53 CST 2015
	 */
	public void setCreateAt(Integer createAt) {
		this.createAt = createAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_rule_keyword.update_by
	 * @return  the value of wx_rule_keyword.update_by
	 * @mbggenerated  Sun Jun 14 20:37:53 CST 2015
	 */
	public Integer getUpdateBy() {
		return updateBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_rule_keyword.update_by
	 * @param updateBy  the value for wx_rule_keyword.update_by
	 * @mbggenerated  Sun Jun 14 20:37:53 CST 2015
	 */
	public void setUpdateBy(Integer updateBy) {
		this.updateBy = updateBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_rule_keyword.update_at
	 * @return  the value of wx_rule_keyword.update_at
	 * @mbggenerated  Sun Jun 14 20:37:53 CST 2015
	 */
	public Integer getUpdateAt() {
		return updateAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_rule_keyword.update_at
	 * @param updateAt  the value for wx_rule_keyword.update_at
	 * @mbggenerated  Sun Jun 14 20:37:53 CST 2015
	 */
	public void setUpdateAt(Integer updateAt) {
		this.updateAt = updateAt;
	}
}