package com.yongjia.model;

public class WxRuleKeyword {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_rule_keyword.id
	 * @mbggenerated  Tue Jul 07 14:25:04 CST 2015
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_rule_keyword.rule_id
	 * @mbggenerated  Tue Jul 07 14:25:04 CST 2015
	 */
	private Long ruleId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_rule_keyword.keyword
	 * @mbggenerated  Tue Jul 07 14:25:04 CST 2015
	 */
	private String keyword;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_rule_keyword.create_by
	 * @mbggenerated  Tue Jul 07 14:25:04 CST 2015
	 */
	private Long createBy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_rule_keyword.create_at
	 * @mbggenerated  Tue Jul 07 14:25:04 CST 2015
	 */
	private Long createAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_rule_keyword.update_by
	 * @mbggenerated  Tue Jul 07 14:25:04 CST 2015
	 */
	private Long updateBy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_rule_keyword.update_at
	 * @mbggenerated  Tue Jul 07 14:25:04 CST 2015
	 */
	private Long updateAt;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_rule_keyword.id
	 * @return  the value of wx_rule_keyword.id
	 * @mbggenerated  Tue Jul 07 14:25:04 CST 2015
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_rule_keyword.id
	 * @param id  the value for wx_rule_keyword.id
	 * @mbggenerated  Tue Jul 07 14:25:04 CST 2015
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_rule_keyword.rule_id
	 * @return  the value of wx_rule_keyword.rule_id
	 * @mbggenerated  Tue Jul 07 14:25:04 CST 2015
	 */
	public Long getRuleId() {
		return ruleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_rule_keyword.rule_id
	 * @param ruleId  the value for wx_rule_keyword.rule_id
	 * @mbggenerated  Tue Jul 07 14:25:04 CST 2015
	 */
	public void setRuleId(Long ruleId) {
		this.ruleId = ruleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_rule_keyword.keyword
	 * @return  the value of wx_rule_keyword.keyword
	 * @mbggenerated  Tue Jul 07 14:25:04 CST 2015
	 */
	public String getKeyword() {
		return keyword;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_rule_keyword.keyword
	 * @param keyword  the value for wx_rule_keyword.keyword
	 * @mbggenerated  Tue Jul 07 14:25:04 CST 2015
	 */
	public void setKeyword(String keyword) {
		this.keyword = keyword;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_rule_keyword.create_by
	 * @return  the value of wx_rule_keyword.create_by
	 * @mbggenerated  Tue Jul 07 14:25:04 CST 2015
	 */
	public Long getCreateBy() {
		return createBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_rule_keyword.create_by
	 * @param createBy  the value for wx_rule_keyword.create_by
	 * @mbggenerated  Tue Jul 07 14:25:04 CST 2015
	 */
	public void setCreateBy(Long createBy) {
		this.createBy = createBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_rule_keyword.create_at
	 * @return  the value of wx_rule_keyword.create_at
	 * @mbggenerated  Tue Jul 07 14:25:04 CST 2015
	 */
	public Long getCreateAt() {
		return createAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_rule_keyword.create_at
	 * @param createAt  the value for wx_rule_keyword.create_at
	 * @mbggenerated  Tue Jul 07 14:25:04 CST 2015
	 */
	public void setCreateAt(Long createAt) {
		this.createAt = createAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_rule_keyword.update_by
	 * @return  the value of wx_rule_keyword.update_by
	 * @mbggenerated  Tue Jul 07 14:25:04 CST 2015
	 */
	public Long getUpdateBy() {
		return updateBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_rule_keyword.update_by
	 * @param updateBy  the value for wx_rule_keyword.update_by
	 * @mbggenerated  Tue Jul 07 14:25:04 CST 2015
	 */
	public void setUpdateBy(Long updateBy) {
		this.updateBy = updateBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_rule_keyword.update_at
	 * @return  the value of wx_rule_keyword.update_at
	 * @mbggenerated  Tue Jul 07 14:25:04 CST 2015
	 */
	public Long getUpdateAt() {
		return updateAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_rule_keyword.update_at
	 * @param updateAt  the value for wx_rule_keyword.update_at
	 * @mbggenerated  Tue Jul 07 14:25:04 CST 2015
	 */
	public void setUpdateAt(Long updateAt) {
		this.updateAt = updateAt;
	}
}