package com.yongjia.model;

public class WxRule {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_rule.id
	 * @mbggenerated  Tue Jul 07 14:25:04 CST 2015
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_rule.name
	 * @mbggenerated  Tue Jul 07 14:25:04 CST 2015
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_rule.msg_id
	 * @mbggenerated  Tue Jul 07 14:25:04 CST 2015
	 */
	private Long msgId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_rule.create_by
	 * @mbggenerated  Tue Jul 07 14:25:04 CST 2015
	 */
	private Long createBy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_rule.create_at
	 * @mbggenerated  Tue Jul 07 14:25:04 CST 2015
	 */
	private Long createAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_rule.update_by
	 * @mbggenerated  Tue Jul 07 14:25:04 CST 2015
	 */
	private Long updateBy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_rule.update_at
	 * @mbggenerated  Tue Jul 07 14:25:04 CST 2015
	 */
	private Long updateAt;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_rule.id
	 * @return  the value of wx_rule.id
	 * @mbggenerated  Tue Jul 07 14:25:04 CST 2015
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_rule.id
	 * @param id  the value for wx_rule.id
	 * @mbggenerated  Tue Jul 07 14:25:04 CST 2015
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_rule.name
	 * @return  the value of wx_rule.name
	 * @mbggenerated  Tue Jul 07 14:25:04 CST 2015
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_rule.name
	 * @param name  the value for wx_rule.name
	 * @mbggenerated  Tue Jul 07 14:25:04 CST 2015
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_rule.msg_id
	 * @return  the value of wx_rule.msg_id
	 * @mbggenerated  Tue Jul 07 14:25:04 CST 2015
	 */
	public Long getMsgId() {
		return msgId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_rule.msg_id
	 * @param msgId  the value for wx_rule.msg_id
	 * @mbggenerated  Tue Jul 07 14:25:04 CST 2015
	 */
	public void setMsgId(Long msgId) {
		this.msgId = msgId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_rule.create_by
	 * @return  the value of wx_rule.create_by
	 * @mbggenerated  Tue Jul 07 14:25:04 CST 2015
	 */
	public Long getCreateBy() {
		return createBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_rule.create_by
	 * @param createBy  the value for wx_rule.create_by
	 * @mbggenerated  Tue Jul 07 14:25:04 CST 2015
	 */
	public void setCreateBy(Long createBy) {
		this.createBy = createBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_rule.create_at
	 * @return  the value of wx_rule.create_at
	 * @mbggenerated  Tue Jul 07 14:25:04 CST 2015
	 */
	public Long getCreateAt() {
		return createAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_rule.create_at
	 * @param createAt  the value for wx_rule.create_at
	 * @mbggenerated  Tue Jul 07 14:25:04 CST 2015
	 */
	public void setCreateAt(Long createAt) {
		this.createAt = createAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_rule.update_by
	 * @return  the value of wx_rule.update_by
	 * @mbggenerated  Tue Jul 07 14:25:04 CST 2015
	 */
	public Long getUpdateBy() {
		return updateBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_rule.update_by
	 * @param updateBy  the value for wx_rule.update_by
	 * @mbggenerated  Tue Jul 07 14:25:04 CST 2015
	 */
	public void setUpdateBy(Long updateBy) {
		this.updateBy = updateBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_rule.update_at
	 * @return  the value of wx_rule.update_at
	 * @mbggenerated  Tue Jul 07 14:25:04 CST 2015
	 */
	public Long getUpdateAt() {
		return updateAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_rule.update_at
	 * @param updateAt  the value for wx_rule.update_at
	 * @mbggenerated  Tue Jul 07 14:25:04 CST 2015
	 */
	public void setUpdateAt(Long updateAt) {
		this.updateAt = updateAt;
	}
}