package com.yongjia.model;

public class WxUser {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_user.openid
	 * @mbggenerated  Sun Jun 14 20:57:12 CST 2015
	 */
	private String openid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_user.subscribe
	 * @mbggenerated  Sun Jun 14 20:57:12 CST 2015
	 */
	private Integer subscribe;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_user.nickname
	 * @mbggenerated  Sun Jun 14 20:57:12 CST 2015
	 */
	private String nickname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_user.sex
	 * @mbggenerated  Sun Jun 14 20:57:12 CST 2015
	 */
	private Integer sex;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_user.language
	 * @mbggenerated  Sun Jun 14 20:57:12 CST 2015
	 */
	private String language;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_user.city
	 * @mbggenerated  Sun Jun 14 20:57:12 CST 2015
	 */
	private String city;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_user.province
	 * @mbggenerated  Sun Jun 14 20:57:12 CST 2015
	 */
	private String province;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_user.country
	 * @mbggenerated  Sun Jun 14 20:57:12 CST 2015
	 */
	private String country;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_user.headimgurl
	 * @mbggenerated  Sun Jun 14 20:57:12 CST 2015
	 */
	private String headimgurl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_user.subscribe_time
	 * @mbggenerated  Sun Jun 14 20:57:12 CST 2015
	 */
	private Integer subscribeTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_user.unionid
	 * @mbggenerated  Sun Jun 14 20:57:12 CST 2015
	 */
	private String unionid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_user.remark
	 * @mbggenerated  Sun Jun 14 20:57:12 CST 2015
	 */
	private String remark;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_user.groupid
	 * @mbggenerated  Sun Jun 14 20:57:12 CST 2015
	 */
	private Integer groupid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_user.ticket
	 * @mbggenerated  Sun Jun 14 20:57:12 CST 2015
	 */
	private String ticket;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_user.openid
	 * @return  the value of wx_user.openid
	 * @mbggenerated  Sun Jun 14 20:57:12 CST 2015
	 */
	public String getOpenid() {
		return openid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_user.openid
	 * @param openid  the value for wx_user.openid
	 * @mbggenerated  Sun Jun 14 20:57:12 CST 2015
	 */
	public void setOpenid(String openid) {
		this.openid = openid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_user.subscribe
	 * @return  the value of wx_user.subscribe
	 * @mbggenerated  Sun Jun 14 20:57:12 CST 2015
	 */
	public Integer getSubscribe() {
		return subscribe;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_user.subscribe
	 * @param subscribe  the value for wx_user.subscribe
	 * @mbggenerated  Sun Jun 14 20:57:12 CST 2015
	 */
	public void setSubscribe(Integer subscribe) {
		this.subscribe = subscribe;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_user.nickname
	 * @return  the value of wx_user.nickname
	 * @mbggenerated  Sun Jun 14 20:57:12 CST 2015
	 */
	public String getNickname() {
		return nickname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_user.nickname
	 * @param nickname  the value for wx_user.nickname
	 * @mbggenerated  Sun Jun 14 20:57:12 CST 2015
	 */
	public void setNickname(String nickname) {
		this.nickname = nickname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_user.sex
	 * @return  the value of wx_user.sex
	 * @mbggenerated  Sun Jun 14 20:57:12 CST 2015
	 */
	public Integer getSex() {
		return sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_user.sex
	 * @param sex  the value for wx_user.sex
	 * @mbggenerated  Sun Jun 14 20:57:12 CST 2015
	 */
	public void setSex(Integer sex) {
		this.sex = sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_user.language
	 * @return  the value of wx_user.language
	 * @mbggenerated  Sun Jun 14 20:57:12 CST 2015
	 */
	public String getLanguage() {
		return language;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_user.language
	 * @param language  the value for wx_user.language
	 * @mbggenerated  Sun Jun 14 20:57:12 CST 2015
	 */
	public void setLanguage(String language) {
		this.language = language;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_user.city
	 * @return  the value of wx_user.city
	 * @mbggenerated  Sun Jun 14 20:57:12 CST 2015
	 */
	public String getCity() {
		return city;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_user.city
	 * @param city  the value for wx_user.city
	 * @mbggenerated  Sun Jun 14 20:57:12 CST 2015
	 */
	public void setCity(String city) {
		this.city = city;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_user.province
	 * @return  the value of wx_user.province
	 * @mbggenerated  Sun Jun 14 20:57:12 CST 2015
	 */
	public String getProvince() {
		return province;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_user.province
	 * @param province  the value for wx_user.province
	 * @mbggenerated  Sun Jun 14 20:57:12 CST 2015
	 */
	public void setProvince(String province) {
		this.province = province;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_user.country
	 * @return  the value of wx_user.country
	 * @mbggenerated  Sun Jun 14 20:57:12 CST 2015
	 */
	public String getCountry() {
		return country;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_user.country
	 * @param country  the value for wx_user.country
	 * @mbggenerated  Sun Jun 14 20:57:12 CST 2015
	 */
	public void setCountry(String country) {
		this.country = country;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_user.headimgurl
	 * @return  the value of wx_user.headimgurl
	 * @mbggenerated  Sun Jun 14 20:57:12 CST 2015
	 */
	public String getHeadimgurl() {
		return headimgurl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_user.headimgurl
	 * @param headimgurl  the value for wx_user.headimgurl
	 * @mbggenerated  Sun Jun 14 20:57:12 CST 2015
	 */
	public void setHeadimgurl(String headimgurl) {
		this.headimgurl = headimgurl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_user.subscribe_time
	 * @return  the value of wx_user.subscribe_time
	 * @mbggenerated  Sun Jun 14 20:57:12 CST 2015
	 */
	public Integer getSubscribeTime() {
		return subscribeTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_user.subscribe_time
	 * @param subscribeTime  the value for wx_user.subscribe_time
	 * @mbggenerated  Sun Jun 14 20:57:12 CST 2015
	 */
	public void setSubscribeTime(Integer subscribeTime) {
		this.subscribeTime = subscribeTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_user.unionid
	 * @return  the value of wx_user.unionid
	 * @mbggenerated  Sun Jun 14 20:57:12 CST 2015
	 */
	public String getUnionid() {
		return unionid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_user.unionid
	 * @param unionid  the value for wx_user.unionid
	 * @mbggenerated  Sun Jun 14 20:57:12 CST 2015
	 */
	public void setUnionid(String unionid) {
		this.unionid = unionid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_user.remark
	 * @return  the value of wx_user.remark
	 * @mbggenerated  Sun Jun 14 20:57:12 CST 2015
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_user.remark
	 * @param remark  the value for wx_user.remark
	 * @mbggenerated  Sun Jun 14 20:57:12 CST 2015
	 */
	public void setRemark(String remark) {
		this.remark = remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_user.groupid
	 * @return  the value of wx_user.groupid
	 * @mbggenerated  Sun Jun 14 20:57:12 CST 2015
	 */
	public Integer getGroupid() {
		return groupid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_user.groupid
	 * @param groupid  the value for wx_user.groupid
	 * @mbggenerated  Sun Jun 14 20:57:12 CST 2015
	 */
	public void setGroupid(Integer groupid) {
		this.groupid = groupid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_user.ticket
	 * @return  the value of wx_user.ticket
	 * @mbggenerated  Sun Jun 14 20:57:12 CST 2015
	 */
	public String getTicket() {
		return ticket;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_user.ticket
	 * @param ticket  the value for wx_user.ticket
	 * @mbggenerated  Sun Jun 14 20:57:12 CST 2015
	 */
	public void setTicket(String ticket) {
		this.ticket = ticket;
	}
}