package com.yongjia.model;

public class WxUserAndMember {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column wx_user.openid
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private String openid;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column wx_user.subscribe
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private Integer subscribe;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column wx_user.nickname
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private String nickname;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column wx_user.sex
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private Integer sex;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column wx_user.language
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private String language;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column wx_user.city
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private String city;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column wx_user.province
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private String province;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column wx_user.country
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private String country;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column wx_user.headimgurl
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private String headimgurl;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * wx_user.subscribe_time
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private Integer subscribe_time;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column wx_user.unionid
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private String unionid;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column wx_user.remark
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private String remark;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column wx_user.groupid
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private Integer groupid;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column wx_user.ticket
     * 
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private String ticket;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * wx_user.openid
     * 
     * @return the value of wx_user.openid
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.id
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private Long id;
    
    private Integer point;

    public Integer getPoint() {
        return point;
    }

    public void setPoint(Integer point) {
        this.point = point;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.name
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.mobile
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.status
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.status
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private Integer valiFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.create_at
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private Long createAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.create_by
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private Long createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.update_at
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private Long updateAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.update_by
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private Long updateBy;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.id
     *
     * @return the value of member.id
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.id
     *
     * @param id the value for member.id
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.name
     *
     * @return the value of member.name
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.name
     *
     * @param name the value for member.name
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.mobile
     *
     * @return the value of member.mobile
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.mobile
     *
     * @param mobile the value for member.mobile
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.status
     *
     * @return the value of member.status
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.status
     *
     * @param status the value for member.status
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    public Integer getValiFlag() {
        return valiFlag;
    }

    public void setValiFlag(Integer valiFlag) {
        this.valiFlag = valiFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.create_at
     *
     * @return the value of member.create_at
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public Long getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.create_at
     *
     * @param createAt the value for member.create_at
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setCreateAt(Long createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.create_by
     *
     * @return the value of member.create_by
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public Long getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.create_by
     *
     * @param createBy the value for member.create_by
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setCreateBy(Long createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.update_at
     *
     * @return the value of member.update_at
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public Long getUpdateAt() {
        return updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.update_at
     *
     * @param updateAt the value for member.update_at
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setUpdateAt(Long updateAt) {
        this.updateAt = updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.update_by
     *
     * @return the value of member.update_by
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public Long getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.update_by
     *
     * @param updateBy the value for member.update_by
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setUpdateBy(Long updateBy) {
        this.updateBy = updateBy;
    }
    
    
    public String getOpenid() {
        return openid;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column wx_user.openid
     * 
     * @param openid the value for wx_user.openid
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setOpenid(String openid) {
        this.openid = openid;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * wx_user.subscribe
     * 
     * @return the value of wx_user.subscribe
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public Integer getSubscribe() {
        return subscribe;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * wx_user.subscribe
     * 
     * @param subscribe the value for wx_user.subscribe
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setSubscribe(Integer subscribe) {
        this.subscribe = subscribe;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * wx_user.nickname
     * 
     * @return the value of wx_user.nickname
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * wx_user.nickname
     * 
     * @param nickname the value for wx_user.nickname
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column wx_user.sex
     * 
     * @return the value of wx_user.sex
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column wx_user.sex
     * 
     * @param sex the value for wx_user.sex
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * wx_user.language
     * 
     * @return the value of wx_user.language
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public String getLanguage() {
        return language;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * wx_user.language
     * 
     * @param language the value for wx_user.language
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setLanguage(String language) {
        this.language = language;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column wx_user.city
     * 
     * @return the value of wx_user.city
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column wx_user.city
     * 
     * @param city the value for wx_user.city
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * wx_user.province
     * 
     * @return the value of wx_user.province
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * wx_user.province
     * 
     * @param province the value for wx_user.province
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setProvince(String province) {
        this.province = province;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * wx_user.country
     * 
     * @return the value of wx_user.country
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column wx_user.country
     * 
     * @param country the value for wx_user.country
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setCountry(String country) {
        this.country = country;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * wx_user.headimgurl
     * 
     * @return the value of wx_user.headimgurl
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public String getHeadimgurl() {
        return headimgurl;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * wx_user.headimgurl
     * 
     * @param headimgurl the value for wx_user.headimgurl
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setHeadimgurl(String headimgurl) {
        this.headimgurl = headimgurl;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * wx_user.subscribe_time
     * 
     * @return the value of wx_user.subscribe_time
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public Integer getSubscribe_time() {
        return subscribe_time;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * wx_user.subscribe_time
     * 
     * @param subscribeTime the value for wx_user.subscribe_time
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setSubscribe_time(Integer subscribe_time) {
        this.subscribe_time = subscribe_time;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * wx_user.unionid
     * 
     * @return the value of wx_user.unionid
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public String getUnionid() {
        return unionid;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column wx_user.unionid
     * 
     * @param unionid the value for wx_user.unionid
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setUnionid(String unionid) {
        this.unionid = unionid;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * wx_user.remark
     * 
     * @return the value of wx_user.remark
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column wx_user.remark
     * 
     * @param remark the value for wx_user.remark
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * wx_user.groupid
     * 
     * @return the value of wx_user.groupid
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public Integer getGroupid() {
        return groupid;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column wx_user.groupid
     * 
     * @param groupid the value for wx_user.groupid
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setGroupid(Integer groupid) {
        this.groupid = groupid;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * wx_user.ticket
     * 
     * @return the value of wx_user.ticket
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public String getTicket() {
        return ticket;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column wx_user.ticket
     * 
     * @param ticket the value for wx_user.ticket
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setTicket(String ticket) {
        this.ticket = ticket;
    }
}