package com.yongjia.model;

public class WxUser2member {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_user2member.id
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_user2member.openid
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private String openid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_user2member.member_id
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private Long memberId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_user2member.id
     *
     * @return the value of wx_user2member.id
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_user2member.id
     *
     * @param id the value for wx_user2member.id
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_user2member.openid
     *
     * @return the value of wx_user2member.openid
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_user2member.openid
     *
     * @param openid the value for wx_user2member.openid
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setOpenid(String openid) {
        this.openid = openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_user2member.member_id
     *
     * @return the value of wx_user2member.member_id
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public Long getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_user2member.member_id
     *
     * @param memberId the value for wx_user2member.member_id
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setMemberId(Long memberId) {
        this.memberId = memberId;
    }
}