package com.yongjia.model;

public class WxUserEmail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_user_email.id
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_user_email.openid
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private String openid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_user_email.title
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_user_email.create_at
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private Integer createAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_user_email.create_by
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private Integer createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_user_email.update_at
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private Integer updateAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_user_email.update_by
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private Integer updateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_user_email.content
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_user_email.id
     *
     * @return the value of wx_user_email.id
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_user_email.id
     *
     * @param id the value for wx_user_email.id
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_user_email.openid
     *
     * @return the value of wx_user_email.openid
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_user_email.openid
     *
     * @param openid the value for wx_user_email.openid
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setOpenid(String openid) {
        this.openid = openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_user_email.title
     *
     * @return the value of wx_user_email.title
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_user_email.title
     *
     * @param title the value for wx_user_email.title
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_user_email.create_at
     *
     * @return the value of wx_user_email.create_at
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public Integer getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_user_email.create_at
     *
     * @param createAt the value for wx_user_email.create_at
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setCreateAt(Integer createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_user_email.create_by
     *
     * @return the value of wx_user_email.create_by
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public Integer getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_user_email.create_by
     *
     * @param createBy the value for wx_user_email.create_by
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setCreateBy(Integer createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_user_email.update_at
     *
     * @return the value of wx_user_email.update_at
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public Integer getUpdateAt() {
        return updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_user_email.update_at
     *
     * @param updateAt the value for wx_user_email.update_at
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setUpdateAt(Integer updateAt) {
        this.updateAt = updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_user_email.update_by
     *
     * @return the value of wx_user_email.update_by
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public Integer getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_user_email.update_by
     *
     * @param updateBy the value for wx_user_email.update_by
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setUpdateBy(Integer updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_user_email.content
     *
     * @return the value of wx_user_email.content
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_user_email.content
     *
     * @param content the value for wx_user_email.content
     *
     * @mbggenerated Tue Jul 07 14:25:04 CST 2015
     */
    public void setContent(String content) {
        this.content = content;
    }
}